package com.delivery.platform.orders.application;
import com.delivery.platform.common.ApiException;import com.delivery.platform.identity.security.IdentityPrincipal;import com.delivery.platform.orders.application.OrdersRepository.ProductSnapshot;import com.delivery.platform.orders.domain.OrderModels.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.util.*;
@Service public class OrdersService {private static final BigDecimal DELIVERY_FEE=new BigDecimal("5.00");private final OrdersRepository repo;public OrdersService(OrdersRepository repo){this.repo=repo;}
 public Cart cart(IdentityPrincipal p){return repo.activeCart(p.tenantId(),p.userId()).map(c->refresh(p,c)).orElse(null);}
 @Transactional public Cart add(IdentityPrincipal p,UUID merchant,UUID branch,UUID product,int quantity,String notes){quantity(quantity);ProductSnapshot item=validProduct(p,merchant,branch,product,quantity);Cart cart=repo.activeCart(p.tenantId(),p.userId()).orElseGet(()->{Cart created=repo.createCart(p.tenantId(),p.userId(),merchant,branch,item.currency());repo.audit(p.tenantId(),p.userId(),"CART_CREATED","CART",created.id());return created;});if(!cart.merchantId().equals(merchant)||!cart.branchId().equals(branch))throw conflict("MIXED_MERCHANT_CART","Vacía el carrito antes de comprar en otro comercio o sucursal");if(!cart.currency().equals(item.currency()))throw conflict("CURRENCY_MISMATCH","Todos los productos deben usar la moneda del carrito");try{repo.addItem(p.tenantId(),cart.id(),product,item.name(),quantity,item.price(),clean(notes));}catch(DataIntegrityViolationException e){throw conflict("DUPLICATE_CART_ITEM","El producto ya está en el carrito; modifica su cantidad");}repo.audit(p.tenantId(),p.userId(),"CART_UPDATED","CART",cart.id());return refresh(p,repo.cart(p.tenantId(),p.userId(),cart.id()));}
 @Transactional public Cart update(IdentityPrincipal p,UUID itemId,int quantity,String notes){quantity(quantity);Cart cart=requiredCart(p);CartItem current=cart.items().stream().filter(x->x.id().equals(itemId)).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CART_ITEM_NOT_FOUND","Producto no encontrado en el carrito"));validProduct(p,cart.merchantId(),cart.branchId(),current.productId(),quantity);repo.updateItem(p.tenantId(),cart.id(),itemId,quantity,clean(notes));repo.audit(p.tenantId(),p.userId(),"CART_UPDATED","CART",cart.id());return refresh(p,repo.cart(p.tenantId(),p.userId(),cart.id()));}
 @Transactional public Cart remove(IdentityPrincipal p,UUID itemId){Cart cart=requiredCart(p);repo.deleteItem(p.tenantId(),cart.id(),itemId);repo.audit(p.tenantId(),p.userId(),"CART_UPDATED","CART",cart.id());return refresh(p,repo.cart(p.tenantId(),p.userId(),cart.id()));}
 @Transactional public void clear(IdentityPrincipal p){repo.activeCart(p.tenantId(),p.userId()).ifPresent(c->{repo.clearCart(p.tenantId(),c.id());repo.audit(p.tenantId(),p.userId(),"CART_CLEARED","CART",c.id());});}
 public List<DeliveryAddress> addresses(IdentityPrincipal p){return repo.addresses(p.tenantId(),p.userId());}
 @Transactional public DeliveryAddress createAddress(IdentityPrincipal p,DeliveryAddress address){return repo.createAddress(p.tenantId(),p.userId(),address);}
 @Transactional public Order checkout(IdentityPrincipal p,UUID addressId,String notes){Cart cart=requiredCart(p);if(cart.items().isEmpty())throw conflict("EMPTY_CART","Agrega al menos un producto antes de continuar");repo.address(p.tenantId(),p.userId(),addressId);cart=refresh(p,cart);for(CartItem item:cart.items()){ProductSnapshot current=validProduct(p,cart.merchantId(),cart.branchId(),item.productId(),item.quantity());if(current.price().compareTo(item.unitPrice())!=0)throw conflict("PRICE_CHANGED","El precio de "+item.productName()+" cambió; revisa el carrito");}Order order=repo.createOrder(p.tenantId(),p.userId(),cart,addressId,clean(notes));repo.checkoutCart(p.tenantId(),cart.id());repo.audit(p.tenantId(),p.userId(),"ORDER_CREATED","ORDER",order.id());repo.audit(p.tenantId(),p.userId(),"CART_CHECKED_OUT","CART",cart.id());return order;}
 public List<Order> orders(IdentityPrincipal p){return repo.orders(p.tenantId(),p.userId());}public Order order(IdentityPrincipal p,UUID id){return repo.order(p.tenantId(),p.userId(),id);}
 @Transactional public Order status(IdentityPrincipal p,UUID id,com.delivery.platform.orders.domain.OrderStatus next,String notes){Order current=order(p,id);if(current.status()==com.delivery.platform.orders.domain.OrderStatus.DELIVERED||current.status()==com.delivery.platform.orders.domain.OrderStatus.CANCELLED||current.status()==com.delivery.platform.orders.domain.OrderStatus.REJECTED)throw conflict("ORDER_FINAL_STATE","Un pedido finalizado no puede modificarse");if(next==com.delivery.platform.orders.domain.OrderStatus.DRAFT)throw conflict("INVALID_ORDER_STATUS","El pedido ya fue creado");repo.updateStatus(p.tenantId(),p.userId(),id,next,clean(notes));repo.audit(p.tenantId(),p.userId(),next==com.delivery.platform.orders.domain.OrderStatus.CANCELLED?"ORDER_CANCELLED":"ORDER_STATUS_CHANGED","ORDER",id);return order(p,id);}
 private Cart requiredCart(IdentityPrincipal p){return repo.activeCart(p.tenantId(),p.userId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CART_NOT_FOUND","No tienes un carrito activo"));}
 private Cart refresh(IdentityPrincipal p,Cart cart){BigDecimal subtotal=BigDecimal.ZERO,tax=BigDecimal.ZERO;for(CartItem i:cart.items()){ProductSnapshot product=repo.product(p.tenantId(),cart.merchantId(),cart.branchId(),i.productId());subtotal=subtotal.add(i.subtotal());tax=tax.add(i.subtotal().multiply(product.taxRate()).divide(new BigDecimal("100"),2,RoundingMode.HALF_UP));}OrderSummary totals=OrderCalculator.calculate(subtotal,tax,BigDecimal.ZERO,cart.items().isEmpty()?BigDecimal.ZERO:DELIVERY_FEE,cart.currency());repo.saveTotals(p.tenantId(),cart.id(),totals);return repo.cart(p.tenantId(),p.userId(),cart.id());}
 private ProductSnapshot validProduct(IdentityPrincipal p,UUID merchant,UUID branch,UUID product,int quantity){ProductSnapshot x=repo.product(p.tenantId(),merchant,branch,product);if(!"ACTIVE".equals(x.merchantStatus()))throw conflict("MERCHANT_INACTIVE","El comercio no está activo");if(!"ACTIVE".equals(x.branchStatus()))throw conflict("BRANCH_CLOSED","La sucursal está cerrada");if(!"PUBLISHED".equals(x.productStatus())||!x.productAvailable()||!x.branchAvailable())throw conflict("PRODUCT_UNAVAILABLE","El producto no está disponible");if(x.price()==null||x.price().signum()<0)throw conflict("INVALID_PRICE","El producto no tiene un precio válido");if(x.trackInventory()&&(x.stock()==null||x.stock().compareTo(BigDecimal.valueOf(quantity))<0))throw conflict("INSUFFICIENT_STOCK","No hay stock suficiente para la cantidad solicitada");return x;}
 private void quantity(int q){if(q<1)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_QUANTITY","La cantidad debe ser al menos 1");}private String clean(String x){return x==null||x.isBlank()?null:x.trim();}private ApiException conflict(String code,String message){return new ApiException(HttpStatus.CONFLICT,code,message);}
}
