package com.delivery.platform.orders.application;

import com.delivery.platform.common.ApiException;
import com.delivery.platform.delivery.application.DeliveryCoverageService;
import com.delivery.platform.identity.security.IdentityPrincipal;
import com.delivery.platform.orders.application.OrdersRepository.*;
import com.delivery.platform.orders.domain.OrderModels.*;
import io.micrometer.core.instrument.MeterRegistry;
import java.math.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service public class OrdersService {
 private final OrdersRepository repo; private final DeliveryCoverageService coverage; private final MeterRegistry metrics;
 public OrdersService(OrdersRepository repo){this(repo,null,null);}
 @Autowired public OrdersService(OrdersRepository repo,DeliveryCoverageService coverage,MeterRegistry metrics){this.repo=repo;this.coverage=coverage;this.metrics=metrics;}
 public Cart cart(IdentityPrincipal p){return repo.activeCart(p.tenantId(),p.userId()).map(c->refresh(p,c)).orElse(null);}
 public Cart add(IdentityPrincipal p,UUID merchant,UUID branch,UUID product,int quantity,String notes){return add(p,merchant,branch,product,quantity,List.of(),notes);}
 @Transactional public Cart add(IdentityPrincipal p,UUID merchant,UUID branch,UUID product,int quantity,List<UUID> optionItemIds,String notes){quantity(quantity);ProductSnapshot item=validProduct(p,merchant,branch,product,quantity);List<OptionSelection> options=validateOptions(p.tenantId(),product,optionItemIds);String optionSignature=signature(options);Cart cart=repo.activeCart(p.tenantId(),p.userId()).orElse(null);if(cart!=null&&cart.items().isEmpty()){repo.checkoutCart(p.tenantId(),cart.id());cart=null;}if(cart==null){cart=repo.createCart(p.tenantId(),p.userId(),merchant,branch,item.currency());repo.audit(p.tenantId(),p.userId(),"CART_CREATED","CART",cart.id());}if(!cart.items().isEmpty()&&(!cart.merchantId().equals(merchant)||!cart.branchId().equals(branch)))throw conflict("MIXED_MERCHANT_CART","Ya tienes productos de otro comercio. Finaliza o vacía el carrito antes de continuar.");if(!cart.currency().equals(item.currency()))throw conflict("CURRENCY_MISMATCH","Todos los productos deben usar la moneda del carrito");try{repo.addItem(p.tenantId(),cart.id(),product,item.name(),quantity,item.price(),options,optionSignature,clean(notes));}catch(DataIntegrityViolationException e){throw conflict("DUPLICATE_CART_ITEM","El producto con esta selección ya está en el carrito; modifica su cantidad");}repo.audit(p.tenantId(),p.userId(),"CART_UPDATED","CART",cart.id());return refresh(p,repo.cart(p.tenantId(),p.userId(),cart.id()));}
 @Transactional public Cart update(IdentityPrincipal p,UUID itemId,int quantity,String notes){quantity(quantity);Cart cart=requiredCart(p);CartItem current=cart.items().stream().filter(x->x.id().equals(itemId)).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CART_ITEM_NOT_FOUND","Producto no encontrado en el carrito"));validProduct(p,cart.merchantId(),cart.branchId(),current.productId(),quantity);validateOptions(p.tenantId(),current.productId(),current.options().stream().map(ItemOption::optionItemId).toList());repo.updateItem(p.tenantId(),cart.id(),itemId,quantity,clean(notes));repo.audit(p.tenantId(),p.userId(),"CART_UPDATED","CART",cart.id());return refresh(p,repo.cart(p.tenantId(),p.userId(),cart.id()));}
 @Transactional public Cart remove(IdentityPrincipal p,UUID itemId){Cart cart=requiredCart(p);repo.deleteItem(p.tenantId(),cart.id(),itemId);repo.audit(p.tenantId(),p.userId(),"CART_UPDATED","CART",cart.id());return refresh(p,repo.cart(p.tenantId(),p.userId(),cart.id()));}
 @Transactional public void clear(IdentityPrincipal p){repo.activeCart(p.tenantId(),p.userId()).ifPresent(c->{repo.clearCart(p.tenantId(),c.id());repo.checkoutCart(p.tenantId(),c.id());repo.audit(p.tenantId(),p.userId(),"CART_CLEARED","CART",c.id());});}
 public List<DeliveryAddress> addresses(IdentityPrincipal p){return repo.addresses(p.tenantId(),p.userId());}
 @Transactional public DeliveryAddress createAddress(IdentityPrincipal p,DeliveryAddress address){return repo.createAddress(p.tenantId(),p.userId(),address);}
 public DeliveryCoverageService.Quote coverage(IdentityPrincipal p,UUID merchantId,UUID addressId){Cart cart=requiredCart(p);if(!cart.merchantId().equals(merchantId))throw new ApiException(HttpStatus.BAD_REQUEST,"CHECKOUT_MERCHANT_INVALID","El comercio no corresponde al carrito activo");repo.address(p.tenantId(),p.userId(),addressId);var quote=coverage.quote(p.tenantId(),p.userId(),cart.merchantId(),cart.branchId(),addressId,cart.subtotal());if(metrics!=null)metrics.counter(quote.eligible()?"checkout_coverage_success":"checkout_coverage_rejected").increment();return quote;}
 public Order checkout(IdentityPrincipal p,UUID addressId,String notes){return checkout(p,addressId,notes,null);}
 @Transactional public Order checkout(IdentityPrincipal p,UUID addressId,String notes,BigDecimal expectedDeliveryFee){Cart cart=requiredCart(p);if(cart.items().isEmpty())throw conflict("EMPTY_CART","Agrega al menos un producto antes de continuar");repo.address(p.tenantId(),p.userId(),addressId);cart=refresh(p,cart);DeliveryCoverageService.Quote quote=coverage==null?null:coverage(p,cart.merchantId(),addressId);if(quote!=null&&!quote.covered())throw conflict(quote.reasonCode(),quote.message());if(quote!=null&&expectedDeliveryFee!=null&&quote.deliveryFee().compareTo(expectedDeliveryFee.setScale(2,RoundingMode.HALF_UP))!=0)throw conflict("DELIVERY_QUOTE_CHANGED","El costo de entrega cambió. Revisa el nuevo total.");for(CartItem item:cart.items()){ProductSnapshot current=validProduct(p,cart.merchantId(),cart.branchId(),item.productId(),item.quantity());if(current.price().compareTo(item.baseUnitPrice())!=0)throw conflict("PRICE_CHANGED","El precio de "+item.productName()+" cambió; revisa el carrito");List<OptionSelection> options=validateOptions(p.tenantId(),item.productId(),item.options().stream().map(ItemOption::optionItemId).toList());BigDecimal currentOptions=options.stream().map(OptionSelection::priceAdjustment).reduce(BigDecimal.ZERO,BigDecimal::add);if(currentOptions.compareTo(item.optionsTotal())!=0)throw conflict("PRICE_CHANGED","El precio de los opcionales de "+item.productName()+" cambió; revisa el carrito");}BigDecimal deliveryFee=quote==null?BigDecimal.ZERO:quote.deliveryFee();OrderSummary totals=OrderCalculator.calculate(cart.subtotal(),cart.tax(),cart.discount(),deliveryFee,cart.currency());repo.saveTotals(p.tenantId(),cart.id(),totals);cart=repo.cart(p.tenantId(),p.userId(),cart.id());Order order=repo.createOrder(p.tenantId(),p.userId(),cart,addressId,clean(notes),quote);repo.checkoutCart(p.tenantId(),cart.id());repo.audit(p.tenantId(),p.userId(),"ORDER_CREATED","ORDER",order.id());repo.audit(p.tenantId(),p.userId(),"CART_CHECKED_OUT","CART",cart.id());return order;}
 @Transactional public Order checkoutWithOptionSnapshots(IdentityPrincipal p,UUID addressId,String notes,BigDecimal expectedDeliveryFee){Cart cart=requiredCart(p);Order order=checkout(p,addressId,notes,expectedDeliveryFee);repo.snapshotOrderItems(p.tenantId(),order.id(),cart.id());return repo.order(p.tenantId(),p.userId(),order.id());}
 public List<Order> orders(IdentityPrincipal p){return repo.orders(p.tenantId(),p.userId());} public Order order(IdentityPrincipal p,UUID id){return repo.order(p.tenantId(),p.userId(),id);}
 @Transactional public Order status(IdentityPrincipal p,UUID id,com.delivery.platform.orders.domain.OrderStatus next,String notes){Order current=order(p,id);if(current.status()==com.delivery.platform.orders.domain.OrderStatus.DELIVERED||current.status()==com.delivery.platform.orders.domain.OrderStatus.CANCELLED||current.status()==com.delivery.platform.orders.domain.OrderStatus.REJECTED)throw conflict("ORDER_FINAL_STATE","Un pedido finalizado no puede modificarse");if(next==com.delivery.platform.orders.domain.OrderStatus.DRAFT)throw conflict("INVALID_ORDER_STATUS","El pedido ya fue creado");repo.updateStatus(p.tenantId(),p.userId(),id,next,clean(notes));repo.audit(p.tenantId(),p.userId(),next==com.delivery.platform.orders.domain.OrderStatus.CANCELLED?"ORDER_CANCELLED":"ORDER_STATUS_CHANGED","ORDER",id);return order(p,id);}
 private Cart requiredCart(IdentityPrincipal p){return repo.activeCart(p.tenantId(),p.userId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CART_NOT_FOUND","No tienes un carrito activo"));}
 private Cart refresh(IdentityPrincipal p,Cart cart){BigDecimal subtotal=BigDecimal.ZERO,tax=BigDecimal.ZERO;for(CartItem i:cart.items()){ProductSnapshot product=repo.product(p.tenantId(),cart.merchantId(),cart.branchId(),i.productId());subtotal=subtotal.add(i.subtotal());tax=tax.add(i.subtotal().multiply(product.taxRate()).divide(new BigDecimal("100"),2,RoundingMode.HALF_UP));}OrderSummary totals=OrderCalculator.calculate(subtotal,tax,BigDecimal.ZERO,BigDecimal.ZERO,cart.currency());repo.saveTotals(p.tenantId(),cart.id(),totals);return repo.cart(p.tenantId(),p.userId(),cart.id());}
 private ProductSnapshot validProduct(IdentityPrincipal p,UUID merchant,UUID branch,UUID product,int quantity){ProductSnapshot x=repo.product(p.tenantId(),merchant,branch,product);if(!"ACTIVE".equals(x.merchantStatus()))throw conflict("MERCHANT_INACTIVE","El comercio no está activo");if(!"ACTIVE".equals(x.branchStatus()))throw conflict("BRANCH_CLOSED","La sucursal está cerrada");if(!"PUBLISHED".equals(x.productStatus())||!x.productAvailable()||!x.branchAvailable())throw conflict("PRODUCT_UNAVAILABLE","El producto no está disponible");if(x.price()==null||x.price().signum()<0)throw conflict("INVALID_PRICE","El producto no tiene un precio válido");if(x.trackInventory()&&(x.stock()==null||x.stock().compareTo(BigDecimal.valueOf(quantity))<0))throw conflict("INSUFFICIENT_STOCK","No hay stock suficiente para la cantidad solicitada");return x;}
 private List<OptionSelection> validateOptions(UUID tenant,UUID product,List<UUID> requested){List<UUID> ids=requested==null?List.of():requested;if(new HashSet<>(ids).size()!=ids.size())throw conflict("DUPLICATE_OPTION_ITEM","No repitas el mismo opcional");Set<UUID> selected=new HashSet<>(ids);List<OptionSelection> result=new ArrayList<>();for(OptionGroupSnapshot group:repo.optionGroups(tenant,product)){List<OptionSelection> matches=group.items().stream().filter(x->selected.remove(x.itemId())).toList();int count=matches.size(),minimum=group.required()?Math.max(1,group.minimumSelections()):group.minimumSelections();if(count<minimum)throw conflict("REQUIRED_OPTIONS_MISSING","Completa las opciones obligatorias de "+group.name());if(group.maximumSelections()!=null&&count>group.maximumSelections())throw conflict("OPTION_LIMIT_EXCEEDED","Selecciona como máximo "+group.maximumSelections()+" opciones de "+group.name());if("SINGLE".equals(group.selectionType())&&count>1)throw conflict("OPTION_SINGLE_SELECTION","Selecciona solo una opción de "+group.name());result.addAll(matches);}if(!selected.isEmpty())throw conflict("INVALID_OPTION_ITEM","Uno de los opcionales no pertenece al producto o no está disponible");return result;}
 private String signature(List<OptionSelection> options){String value=options.stream().map(x->x.itemId().toString()).sorted().reduce((a,b)->a+","+b).orElse("");try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private void quantity(int q){if(q<1)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_QUANTITY","La cantidad debe ser al menos 1");} private String clean(String x){return x==null||x.isBlank()?null:x.trim();} private ApiException conflict(String code,String message){return new ApiException(HttpStatus.CONFLICT,code,message);}
}
