'use client';

import {FormEvent,useCallback,useEffect,useState} from 'react';
import {RefreshCw,Search,X} from 'lucide-react';
import {api,ApiError} from '@/lib/api';
import {useMerchant} from '@/lib/merchant';
import {useAuth} from '@/lib/auth';
import type{AssignmentInfo,AvailableCourier,OrderDetail,OrderRow,Page,StatusCount}from'@/lib/types';
import './orders.css';

const labels:Record<string,string>={PENDING:'Nuevo',CONFIRMED:'Aceptado',PREPARING:'En preparación',READY:'Listo para recoger',SEARCHING_COURIER:'Buscando repartidor',ASSIGNED:'Repartidor asignado',COURIER_ASSIGNED:'Repartidor asignado',PICKED_UP:'Entregado al repartidor',ON_THE_WAY:'En camino al cliente',DELIVERED:'Recibido por el cliente',REJECTED:'Rechazado',CANCELLED:'Cancelado'};
const states=['','PENDING','CONFIRMED','PREPARING','READY','SEARCHING_COURIER','COURIER_ASSIGNED','PICKED_UP','ON_THE_WAY','DELIVERED','REJECTED','CANCELLED'];
const money=(n:number,c:string)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:c}).format(n);
const age=(d:string)=>`${Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/60000))} min`;

export default function Orders(){
 const{merchantId,branchId}=useMerchant();const{me}=useAuth();const[rows,setRows]=useState<OrderRow[]>([]);const[counts,setCounts]=useState<StatusCount[]>([]);const[detail,setDetail]=useState<OrderDetail|null>(null);const[assignment,setAssignment]=useState<AssignmentInfo|null>(null);const[state,setState]=useState('');const[search,setSearch]=useState('');const[page,setPage]=useState(0);const[pages,setPages]=useState(0);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[showCouriers,setShowCouriers]=useState(false);const[courierSearch,setCourierSearch]=useState('');const[couriers,setCouriers]=useState<AvailableCourier[]>([]);
 const can=(p:string)=>!!me?.permissions.includes(p);
 const load=useCallback(async()=>{if(!merchantId)return;setLoading(true);try{const q=new URLSearchParams({merchantId,page:String(page),size:'20'});if(branchId)q.set('branchId',branchId);if(state)q.set('status',state);if(search)q.set('search',search);const[c,s]=await Promise.all([api<Page<OrderRow>>(`/api/v1/merchant/orders?${q}`),api<StatusCount[]>(`/api/v1/merchant/orders/status-counts?merchantId=${merchantId}${branchId?`&branchId=${branchId}`:''}`)]);setRows(c.content);setPages(c.totalPages);setCounts(s)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[merchantId,branchId,state,search,page]);
 useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load()};const timer=setInterval(refresh,10000);document.addEventListener('visibilitychange',refresh);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('focus',refresh)}},[load]);
 async function open(id:string){setError('');try{const d=await api<OrderDetail>(`/api/v1/merchant/orders/${id}`);setDetail(d);setAssignment(await api<AssignmentInfo>(`/api/v1/merchant/orders/${id}/delivery/assignment`).catch(()=>null))}catch(e){setError((e as Error).message)}}
 async function transition(status:string){if(!detail)return;let reason;if(status==='REJECTED'){reason=prompt('Motivo del rechazo')??'';if(!reason)return}try{const d=await api<OrderDetail>(`/api/v1/merchant/orders/${detail.order.id}/status`,{method:'PATCH',body:JSON.stringify({status,expectedVersion:detail.order.version,reason})});setDetail(d);await load()}catch(e){setError((e as Error).message)}}
 async function assign(kind:'auto'|'manual',courierId?:string){if(!detail)return;const name=couriers.find(x=>x.id===courierId)?.name;if(!confirm(kind==='auto'?'¿Confirmas la asignación automática? El sistema notificará al repartidor disponible para que acepte la entrega.':`¿Confirmas la asignación del pedido a ${name}? Al continuar, el repartidor recibirá una notificación para aceptar la entrega.`))return;try{const a=await api<AssignmentInfo>(`/api/v1/merchant/orders/${detail.order.id}/delivery/${kind==='auto'?'auto-assign':'manual-assign'}`,{method:'POST',body:kind==='manual'?JSON.stringify({courierId}):undefined});setAssignment(a);setNotice('Asignación enviada correctamente. El repartidor ha sido notificado y debe aceptar la entrega.');setShowCouriers(false);await open(detail.order.id);await load()}catch(e){setError(e instanceof ApiError&&e.status===409&&e.message.includes('asignado')?'El pedido ya fue asignado por otro usuario.':(e as Error).message)}}
 async function findCouriers(e?:FormEvent){e?.preventDefault();if(!detail)return;try{const q=new URLSearchParams({search:courierSearch,size:'20'});const result=await api<Page<AvailableCourier>>(`/api/v1/merchant/orders/${detail.order.id}/delivery/available-couriers?${q}`);setCouriers(result.content);setShowCouriers(true)}catch(e){setError((e as Error).message)}}
 async function hand(){if(!detail||!confirm('¿Confirmas que el pedido fue entregado al repartidor?'))return;try{setAssignment(await api(`/api/v1/merchant/orders/${detail.order.id}/hand-to-courier`,{method:'POST'}));setNotice('Pedido entregado al repartidor.');await open(detail.order.id);await load()}catch(e){setError((e as Error).message)}}
 const total=counts.reduce((n,x)=>n+x.count,0),count=(s:string)=>counts.find(x=>x.status===s)?.count??0;
 return <section className="page"><div className="title"><div><h1>Pedidos</h1><p>Lista operativa · actualización cada 10 segundos</p></div><button className="secondary" onClick={load}><RefreshCw className={loading?'spin':''}/>Actualizar</button></div>
 <div className="order-counts"><button className={!state?'selected':''}onClick={()=>{setState('');setPage(0)}}>Todos <b>{total}</b></button>{states.slice(1).map(s=><button key={s}className={state===s?'selected':''}onClick={()=>{setState(s);setPage(0)}}>{labels[s]??s} <b>{count(s)}</b></button>)}</div>
 <div className="order-filters"><label>Estado del pedido<select value={state}onChange={e=>{setState(e.target.value);setPage(0)}}>{states.map(s=><option key={s}value={s}>{s?labels[s]??s:'Todos'}</option>)}</select></label><label className="toolbar"><Search/><input aria-label="Buscar pedidos"placeholder="Pedido, cliente o repartidor"value={search}onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label></div>
 {notice&&<div className="notice">{notice}</div>}{error&&<div className="alert"role="alert">{error}</div>}{loading&&!rows.length?<div className="empty">Cargando pedidos…</div>:<div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Pedido</th><th>Fecha y hora</th><th>Cliente</th><th>Sucursal</th><th>Total</th><th>Estado</th><th>Entrega</th><th>Repartidor</th><th>Pago</th><th>Tiempo</th><th>Acción</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><strong>#{o.orderNumber}</strong></td><td>{new Date(o.createdAt).toLocaleString('es-PE')}</td><td>{o.customerName}</td><td>{o.branchName}</td><td>{money(o.total,o.currency)}</td><td><span className="status">{labels[o.status]??o.status}</span></td><td>{o.deliveryStatus?labels[o.deliveryStatus]??o.deliveryStatus:'—'}</td><td>{o.courierName??'Sin asignar'}</td><td>{o.paymentMethod??o.paymentStatus}</td><td>{age(o.createdAt)}</td><td><button className="secondary compact"onClick={()=>open(o.id)}>Ver detalle</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No hay pedidos con el estado seleccionado.</div>}</div>}
 <div className="pagination"><button className="secondary"disabled={page===0}onClick={()=>setPage(x=>x-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,pages)}</span><button className="secondary"disabled={page+1>=pages}onClick={()=>setPage(x=>x+1)}>Siguiente</button></div>
 {detail&&<div className="drawer-backdrop"onClick={()=>setDetail(null)}><aside className="drawer order-detail"onClick={e=>e.stopPropagation()}><button className="close"aria-label="Cerrar"onClick={()=>setDetail(null)}><X/></button><h2>Pedido #{detail.order.orderNumber}</h2><span className="status">{labels[detail.order.status]??detail.order.status}</span><div className="customer"><strong>{detail.order.customerName}</strong><span>{detail.phone}</span><span>{detail.address}, {detail.district}</span></div><h3>Productos</h3>{detail.items.map((x,i)=><div className="item"key={i}><span>{x.quantity} × {x.productName}</span><b>{money(x.subtotal,detail.order.currency)}</b></div>)}<div className="total"><span>Total</span><strong>{money(detail.order.total,detail.order.currency)}</strong></div><section className="assignment"><h3>Asignación de repartidor</h3><dl><div><dt>Estado</dt><dd>{assignment?.assignmentStatus??'Sin asignación'}</dd></div><div><dt>Repartidor</dt><dd>{assignment?.courierName??'—'}</dd></div><div><dt>Vehículo</dt><dd>{assignment?.vehicleType??'—'}</dd></div><div><dt>Disponibilidad</dt><dd>{assignment?.courierStatus??'—'}</dd></div><div><dt>Asignado</dt><dd>{assignment?.assignedAt?new Date(assignment.assignedAt).toLocaleString('es-PE'):'—'}</dd></div><div><dt>Última ubicación</dt><dd>{assignment?.latitude?`${assignment.latitude}, ${assignment.longitude}`:'No disponible'}</dd></div></dl>{assignment?.message&&<p className="assignment-message">{assignment.message} {assignment.message.includes('no aceptado')&&'Puedes intentar asignarlo nuevamente.'}</p>}<div className="actions">{can('MERCHANT_DELIVERY_ASSIGN')&&detail.order.status==='READY'&&assignment?.assignmentStatus!=='PENDING'&&assignment?.assignmentStatus!=='ACCEPTED'&&<><button onClick={()=>assign('auto')}>Asignar automáticamente</button><button className="secondary"onClick={()=>findCouriers()}>Seleccionar repartidor</button></>}{can('MERCHANT_ORDER_HAND_TO_COURIER')&&detail.order.status==='READY'&&assignment?.assignmentStatus==='ACCEPTED'&&<button onClick={hand}>Entregar al repartidor</button>}</div></section><Actions status={detail.order.status}run={transition}/></aside></div>}
 {showCouriers&&<div className="modal-backdrop"onClick={()=>setShowCouriers(false)}><section className="courier-modal"onClick={e=>e.stopPropagation()}><button className="close"onClick={()=>setShowCouriers(false)}><X/></button><h2>Repartidores disponibles</h2><form className="toolbar"onSubmit={findCouriers}><Search/><input placeholder="Nombre, código, placa o vehículo"value={courierSearch}onChange={e=>setCourierSearch(e.target.value)}/></form><div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>Repartidor</th><th>Vehículo</th><th>Estado</th><th>Distancia</th><th>Pedidos activos</th><th>Acción</th></tr></thead><tbody>{couriers.map(c=><tr key={c.id}><td>{c.name}<br/><small>{c.code.slice(0,8)}</small></td><td>{c.vehicleType}<br/><small>{c.partialPlate??'Sin placa'}</small></td><td>{c.status}</td><td>{c.distanceKm?`${c.distanceKm} km`:'—'}</td><td>{c.activeOrders}</td><td><button onClick={()=>assign('manual',c.id)}>Seleccionar</button></td></tr>)}</tbody></table>{!couriers.length&&<div className="empty">No se encontraron repartidores disponibles.</div>}</div></section></div>}</section>;
}
function Actions({status,run}:{status:string;run:(s:string)=>void}){if(status==='PENDING')return <div className="actions"><button className="danger"onClick={()=>run('REJECTED')}>Rechazar</button><button onClick={()=>run('CONFIRMED')}>Aceptar pedido</button></div>;if(status==='CONFIRMED')return <button onClick={()=>run('PREPARING')}>Iniciar preparación</button>;if(status==='PREPARING')return <button onClick={()=>run('READY')}>Pedido preparado</button>;return null}
