'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,ApiClientError} from '@/lib/api';

export default function NewProduct(){
  const[merchantId,setMerchant]=useState('');
  useEffect(()=>setMerchant(new URLSearchParams(location.search).get('merchantId')??''),[]);
  const[d,setD]=useState({name:'',slug:'',sku:'',description:'',productType:'SIMPLE',basePrice:0,currency:'PEN',trackInventory:false,stockQuantity:0,available:true,featured:false,categoryId:null});
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');const router=useRouter();
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const product=await api<{id:string}>(`/api/v1/merchants/${merchantId}/products`,{method:'POST',body:JSON.stringify(d)});router.push(`/products/${product.id}`)}catch(e){setError(e instanceof ApiClientError?e.message:'No se pudo crear el producto')}finally{setBusy(false)}}
  return <><p className="eyebrow">CATÁLOGO</p><h1>Nuevo producto</h1>{error&&<div className="error" role="alert">{error}</div>}<form className="panel catalog-form" onSubmit={submit}><label>Nombre<input value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></label><label>Slug<input value={d.slug} onChange={e=>setD({...d,slug:e.target.value})} placeholder="Se genera desde el nombre"/></label><label>SKU<input value={d.sku} onChange={e=>setD({...d,sku:e.target.value})}/></label><label>Tipo<select value={d.productType} onChange={e=>setD({...d,productType:e.target.value})}>{['SIMPLE','VARIABLE','COMBO','SERVICE'].map(x=><option key={x}>{x}</option>)}</select></label><label>Precio<input type="number" min="0" step="0.01" value={d.basePrice} onChange={e=>setD({...d,basePrice:Number(e.target.value)})}/></label><label>Moneda<input value={d.currency} maxLength={3} onChange={e=>setD({...d,currency:e.target.value.toUpperCase()})}/></label><label className="full">Descripción<textarea value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></label><label className="option-choice full"><input type="checkbox" checked={d.trackInventory} onChange={e=>setD({...d,trackInventory:e.target.checked})}/><span><strong>Controlar inventario</strong><small>Incluye este producto en el módulo Inventario y valida sus existencias.</small></span></label>{d.trackInventory&&<label>Stock inicial<input type="number" min="0" step="0.001" value={d.stockQuantity} onChange={e=>setD({...d,stockQuantity:Number(e.target.value)})} required/></label>}<div className="form-actions"><Link className="button secondary" href={merchantId?`/merchants/${merchantId}/products`:'/merchants'}>Cancelar</Link><button disabled={busy||!merchantId}>{busy?'Guardando…':'Crear producto'}</button></div></form></>
}
