package com.delivery.platform.identity.auth.application;
import com.delivery.platform.common.ApiException; import com.delivery.platform.identity.auth.api.AuthDtos.*; import com.delivery.platform.identity.security.*;
import org.springframework.beans.factory.annotation.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.mail.SimpleMailMessage; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import java.util.HexFormat;
@Service public class AuthService {
 static final String GRANT_ALL_PERMISSIONS_SQL =
  "insert into role_permissions(role_id,permission_id) select :r,id from permissions on conflict do nothing";
 private final JdbcClient db; private final PasswordEncoder passwords; private final JwtService jwt; private final JavaMailSender mail; private final SecureRandom random=new SecureRandom();
 @Value("${identity.refresh-days}")long refreshDays; @Value("${identity.reset-minutes}")long resetMinutes; @Value("${identity.frontend-url}")String frontendUrl; @Value("${identity.login-max-attempts}")int maxAttempts; @Value("${identity.login-lock-minutes}")long lockMinutes;
 public AuthService(JdbcClient db,PasswordEncoder passwords,JwtService jwt,JavaMailSender mail){this.db=db;this.passwords=passwords;this.jwt=jwt;this.mail=mail;}
 record UserRow(UUID id,UUID tenantId,String tenantCode,String tenantName,String email,String passwordHash,String firstName,String lastName,String userStatus,String tenantStatus,int attempts,Instant lockedUntil,boolean mustChangePassword){}
 @Transactional public Session register(RegisterTenant q,String ip,String agent){if(db.sql("select count(*) from tenants where code=:c").param("c",q.tenantCode()).query(Integer.class).single()>0)throw new ApiException(HttpStatus.CONFLICT,"TENANT_CODE_EXISTS","El código de empresa ya está registrado");UUID t=UUID.randomUUID(),u=UUID.randomUUID(),r=UUID.randomUUID();db.sql("insert into tenants(id,code,name,status) values(:id,:c,:n,'ACTIVE')").param("id",t).param("c",q.tenantCode()).param("n",q.tenantName()).update();db.sql("insert into users(id,tenant_id,email,password_hash,first_name,last_name,status) values(:id,:t,:e,:p,:f,:l,'ACTIVE')").param("id",u).param("t",t).param("e",q.adminEmail().trim().toLowerCase()).param("p",passwords.encode(q.adminPassword())).param("f",q.adminFirstName()).param("l",q.adminLastName()).update();db.sql("insert into roles(id,tenant_id,code,name,description,system_role) values(:id,:t,'TENANT_ADMIN','Administrador del tenant','Administración completa',true)").param("id",r).param("t",t).update();db.sql(GRANT_ALL_PERMISSIONS_SQL).param("r",r).update();db.sql("insert into user_roles values(:u,:r)").param("u",u).param("r",r).update();audit(t,u,"TENANT_REGISTERED","TENANT",t,ip,agent);return session(load(u),ip,agent);}
 @Transactional public Session registerCustomer(RegisterCustomer q,String ip,String agent){UUID tenant=db.sql("select id from tenants where code=:code and status='ACTIVE'").param("code",q.tenantCode()).query(UUID.class).optional().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"TENANT_NOT_FOUND","Empresa no encontrada"));String email=q.email().trim().toLowerCase();if(db.sql("select count(*) from users where tenant_id=:tenant and lower(email)=:email").param("tenant",tenant).param("email",email).query(Integer.class).single()>0)throw new ApiException(HttpStatus.CONFLICT,"EMAIL_EXISTS","El correo ya está registrado");UUID user=UUID.randomUUID();db.sql("insert into users(id,tenant_id,email,password_hash,first_name,last_name,status) values(:id,:tenant,:email,:password,:first,:last,'ACTIVE')").param("id",user).param("tenant",tenant).param("email",email).param("password",passwords.encode(q.password())).param("first",q.firstName().trim()).param("last",q.lastName().trim()).update();int assigned=db.sql("insert into user_roles(user_id,role_id) select :user,id from roles where tenant_id=:tenant and code='CUSTOMER' and active on conflict do nothing").param("user",user).param("tenant",tenant).update();if(assigned==0)throw new ApiException(HttpStatus.CONFLICT,"CUSTOMER_ROLE_MISSING","El rol de cliente no está configurado");audit(tenant,user,"CUSTOMER_REGISTERED","USER",user,ip,agent);return session(load(user),ip,agent);}
 @Transactional public Session login(Login q,String ip,String agent){UserRow u=findLogin(q.tenantCode(),q.email());if(!"ACTIVE".equals(u.tenantStatus())||!"ACTIVE".equals(u.userStatus()))throw invalid();if(u.lockedUntil()!=null&&u.lockedUntil().isAfter(Instant.now()))throw new ApiException(HttpStatus.LOCKED,"ACCOUNT_LOCKED","La cuenta está temporalmente bloqueada");if(!passwords.matches(q.password(),u.passwordHash())){int n=u.attempts()+1;Instant until=n>=maxAttempts?Instant.now().plus(lockMinutes,java.time.temporal.ChronoUnit.MINUTES):null;boolean lock=until!=null;db.sql("update users set failed_login_attempts=:n,locked_until=:l,status=case when :lock then 'LOCKED' else status end where id=:id").param("n",n).param("l",until).param("lock",lock).param("id",u.id()).update();audit(u.tenantId(),u.id(),"LOGIN_FAILED",null,null,ip,agent);throw invalid();}db.sql("update users set failed_login_attempts=0,locked_until=null,status='ACTIVE',last_login_at=now() where id=:id").param("id",u.id()).update();audit(u.tenantId(),u.id(),"LOGIN_SUCCESS",null,null,ip,agent);return session(load(u.id()),ip,agent);}
 @Transactional public Session refresh(String raw,String ip,String agent){if(raw==null||raw.isBlank())throw token();String hash=hash(raw);UUID user=db.sql("select user_id from refresh_tokens where token_hash=:h and revoked_at is null and expires_at>now() for update").param("h",hash).query(UUID.class).optional().orElseThrow(this::token);db.sql("update refresh_tokens set revoked_at=now() where token_hash=:h").param("h",hash).update();return session(load(user),ip,agent);}
 @Transactional public void logout(String raw,IdentityPrincipal p,String ip,String agent){if(raw!=null)db.sql("update refresh_tokens set revoked_at=now() where token_hash=:h and user_id=:u").param("h",hash(raw)).param("u",p.userId()).update();audit(p.tenantId(),p.userId(),"LOGOUT",null,null,ip,agent);}
 @Transactional public void forgot(Forgot q,String ip,String agent){findOptional(q.tenantCode(),q.email()).ifPresent(u->{String raw=randomToken();db.sql("insert into password_reset_tokens(user_id,token_hash,expires_at) values(:u,:h,:x)").param("u",u.id()).param("h",hash(raw)).param("x",OffsetDateTime.now(ZoneOffset.UTC).plusMinutes(resetMinutes)).update();audit(u.tenantId(),u.id(),"PASSWORD_RESET_REQUESTED",null,null,ip,agent);try{var m=new SimpleMailMessage();m.setTo(u.email());m.setSubject("Restablecer contraseña");m.setText("Abre este enlace para restablecer tu contraseña: "+frontendUrl+"/reset-password?token="+raw);mail.send(m);}catch(Exception ignored){}});}
 @Transactional public void reset(Reset q,String ip,String agent){UUID u=db.sql("select user_id from password_reset_tokens where token_hash=:h and used_at is null and expires_at>now() for update").param("h",hash(q.token())).query(UUID.class).optional().orElseThrow(this::token);db.sql("update password_reset_tokens set used_at=now() where token_hash=:h").param("h",hash(q.token())).update();db.sql("update users set password_hash=:p,failed_login_attempts=0,locked_until=null,status='ACTIVE' where id=:u").param("p",passwords.encode(q.newPassword())).param("u",u).update();db.sql("update refresh_tokens set revoked_at=now() where user_id=:u and revoked_at is null").param("u",u).update();var row=load(u);audit(row.tenantId(),u,"PASSWORD_RESET_COMPLETED",null,null,ip,agent);}
 @Transactional public void changePassword(IdentityPrincipal p,ChangePassword q,String ip,String agent){UserRow u=load(p.userId());if(!passwords.matches(q.currentPassword(),u.passwordHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"CURRENT_PASSWORD_INVALID","La contraseña actual es incorrecta");if(passwords.matches(q.newPassword(),u.passwordHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"PASSWORD_REUSED","La nueva contraseña debe ser diferente");db.sql("update users set password_hash=:password,must_change_password=false,updated_at=now() where id=:user and tenant_id=:tenant").param("password",passwords.encode(q.newPassword())).param("user",p.userId()).param("tenant",p.tenantId()).update();audit(p.tenantId(),p.userId(),"PASSWORD_CHANGED","USER",p.userId(),ip,agent);}
 public Me me(IdentityPrincipal p){return toMe(load(p.userId()));}
 public record Session(Tokens response,String refreshToken){}
 private Session session(UserRow u,String ip,String agent){var p=principal(u);String raw=randomToken();db.sql("insert into refresh_tokens(user_id,token_hash,expires_at,created_ip,user_agent) values(:u,:h,:x,:ip,:a)").param("u",u.id()).param("h",hash(raw)).param("x",OffsetDateTime.now(ZoneOffset.UTC).plusDays(refreshDays)).param("ip",ip).param("a",agent).update();return new Session(new Tokens(jwt.issue(p),jwt.expiresIn(),toMe(u)),raw);}
 private IdentityPrincipal principal(UserRow u){Set<String> roles=new HashSet<>(db.sql("select r.code from roles r join user_roles ur on ur.role_id=r.id where ur.user_id=:u and r.active").param("u",u.id()).query(String.class).list());Set<String> perms=new HashSet<>(db.sql("select distinct p.code from permissions p join role_permissions rp on rp.permission_id=p.id join user_roles ur on ur.role_id=rp.role_id where ur.user_id=:u").param("u",u.id()).query(String.class).list());return new IdentityPrincipal(u.id(),u.tenantId(),u.tenantCode(),roles,perms);}
 private Me toMe(UserRow u){var p=principal(u);return new Me(u.id(),new Tenant(u.tenantId(),u.tenantCode(),u.tenantName()),u.firstName(),u.lastName(),u.email(),p.roles(),p.permissions(),u.mustChangePassword());}
 private UserRow findLogin(String code,String email){return findOptional(code,email).orElseThrow(this::invalid);}
 private Optional<UserRow> findOptional(String code,String email){return db.sql("select u.id,u.tenant_id,t.code tenant_code,t.name tenant_name,u.email,u.password_hash,u.first_name,u.last_name,u.status user_status,t.status tenant_status,u.failed_login_attempts attempts,u.locked_until,u.must_change_password from users u join tenants t on t.id=u.tenant_id where t.code=:c and (lower(u.email)=lower(:e) or lower(u.username)=lower(:e))").param("c",code).param("e",email).query(UserRow.class).optional();}
 private UserRow load(UUID id){return db.sql("select u.id,u.tenant_id,t.code tenant_code,t.name tenant_name,u.email,u.password_hash,u.first_name,u.last_name,u.status user_status,t.status tenant_status,u.failed_login_attempts attempts,u.locked_until,u.must_change_password from users u join tenants t on t.id=u.tenant_id where u.id=:id").param("id",id).query(UserRow.class).single();}
 private void audit(UUID t,UUID u,String action,String type,UUID entity,String ip,String agent){db.sql("insert into audit_logs(tenant_id,user_id,action,entity_type,entity_id,ip_address,user_agent) values(:t,:u,:a,:y,:e,:ip,:ag)").param("t",t).param("u",u).param("a",action).param("y",type).param("e",entity).param("ip",ip).param("ag",agent).update();}
 private String randomToken(){byte[]b=new byte[48];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private ApiException invalid(){return new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Credenciales inválidas");} private ApiException token(){return new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_TOKEN","Token inválido o expirado");}
}
