'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ChartNoAxesCombined, RefreshCw } from 'lucide-react';
import { api } from '@/lib/api';
import { useMerchant } from '@/lib/merchant';
import { ModulePage } from '@/components/module-page';
import './reports.css';

type Metric={status:string;orders:number;total:number};type Daily={date:string;orders:number;total:number};type Report={totalOrders:number;completedOrders:number;cancelledOrders:number;grossSales:number;averageTicket:number;byStatus:Metric[];daily:Daily[]};
const labels:Record<string,string>={PENDING:'Nuevos',CONFIRMED:'Aceptados',PREPARING:'En preparación',READY:'Listos',ASSIGNED:'Asignados',PICKED_UP:'Recogidos',ON_THE_WAY:'En camino',DELIVERED:'Completados',CANCELLED:'Cancelados',REJECTED:'Rechazados'};
const money=(value:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(value)||0);

export default function Reports(){const{merchantId,branchId}=useMerchant();const[days,setDays]=useState(30);const[data,setData]=useState<Report|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const load=useCallback(async()=>{if(!merchantId)return;setLoading(true);setError('');const params=new URLSearchParams({merchantId,days:String(days)});if(branchId)params.set('branchId',branchId);try{setData(await api<Report>(`/api/v1/merchant/reports/summary?${params}`))}catch(caught){setError((caught as Error).message);setData(null)}finally{setLoading(false)}},[merchantId,branchId,days]);
 useEffect(()=>{void load()},[load]);const max=useMemo(()=>Math.max(1,...(data?.daily.map(x=>Number(x.total))??[])),[data]);
 return <ModulePage title="Reportes"description="Indicadores operativos y ventas"icon={ChartNoAxesCombined}><div className="report-toolbar"><label>Periodo<select value={days}onChange={e=>setDays(Number(e.target.value))}><option value={7}>Últimos 7 días</option><option value={30}>Últimos 30 días</option><option value={90}>Últimos 90 días</option><option value={365}>Último año</option></select></label><button className="secondary"onClick={load}disabled={loading}><RefreshCw className={loading?'spin':''}/>Actualizar</button></div>{error&&<div className="alert"role="alert">{error}</div>}{loading&&!data?<div className="empty">Cargando indicadores…</div>:data&&<><div className="report-cards"><article><span>Ventas</span><strong>{money(data.grossSales)}</strong></article><article><span>Pedidos</span><strong>{data.totalOrders}</strong></article><article><span>Ticket promedio</span><strong>{money(data.averageTicket)}</strong></article><article><span>Completados</span><strong>{data.completedOrders}</strong></article><article><span>Cancelados / rechazados</span><strong>{data.cancelledOrders}</strong></article></div><div className="report-grid"><section className="panel"><h2>Ventas por día</h2>{data.daily.length===0?<div className="empty">Aún no hay pedidos en este periodo.</div>:<div className="daily-chart">{data.daily.map(day=><div className="bar-row"key={day.date}><time>{new Date(`${day.date}T12:00:00`).toLocaleDateString('es-PE',{day:'2-digit',month:'short'})}</time><div><i style={{width:`${Math.max(2,Number(day.total)/max*100)}%`}}/></div><strong>{money(day.total)}</strong></div>)}</div>}</section><section className="panel"><h2>Pedidos por estado</h2>{data.byStatus.length===0?<div className="empty">Sin pedidos</div>:data.byStatus.map(item=><div className="status-metric"key={item.status}><span className="status">{labels[item.status]??item.status}</span><strong>{item.orders}</strong><small>{money(item.total)}</small></div>)}</section></div></>}</ModulePage>}
