package com.delivery.platform.catalog.category.api;
import com.delivery.platform.catalog.common.CatalogSupport;import com.delivery.platform.common.ApiException;import com.delivery.platform.identity.security.IdentityPrincipal;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController public class CategoryController {private final JdbcClient db;private final CatalogSupport support;public CategoryController(JdbcClient d,CatalogSupport s){db=d;support=s;}public record Category(UUID id,UUID merchantId,UUID parentId,String code,String name,String description,int sortOrder,boolean active){}public record Save(UUID parentId,@NotBlank String code,@NotBlank String name,String description,Integer sortOrder){}public record Active(boolean active){}
 @GetMapping("/api/v1/merchants/{merchantId}/categories") @PreAuthorize("hasAuthority('CATALOG_CATEGORIES_VIEW')") List<Category> list(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID merchantId){support.merchant(p,merchantId);return db.sql("select * from categories where tenant_id=:t and merchant_id=:m order by sort_order,name").param("t",p.tenantId()).param("m",merchantId).query((r,n)->map(r)).list();}
 @PostMapping("/api/v1/merchants/{merchantId}/categories") @Transactional @PreAuthorize("hasAuthority('CATALOG_CATEGORIES_CREATE')") Category create(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID merchantId,@Valid @RequestBody Save q){support.merchant(p,merchantId);validateParent(p,merchantId,null,q.parentId());UUID id=UUID.randomUUID();db.sql("insert into categories(id,tenant_id,merchant_id,parent_id,code,name,description,sort_order) values(:i,:t,:m,:p,lower(:c),:n,:d,:o)").param("i",id).param("t",p.tenantId()).param("m",merchantId).param("p",q.parentId()).param("c",q.code()).param("n",q.name()).param("d",q.description()).param("o",q.sortOrder()==null?0:q.sortOrder()).update();support.audit(p,"CATEGORY_CREATED","CATEGORY",id);return one(p,id);}
 @GetMapping("/api/v1/categories/{id}") @PreAuthorize("hasAuthority('CATALOG_CATEGORIES_VIEW')") Category one(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){support.category(p,id);return db.sql("select * from categories where id=:i").param("i",id).query((r,n)->map(r)).single();}
 @PutMapping("/api/v1/categories/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_CATEGORIES_UPDATE')") Category update(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody Save q){Category old=one(p,id);validateParent(p,old.merchantId(),id,q.parentId());db.sql("update categories set parent_id=:p,code=lower(:c),name=:n,description=:d,sort_order=:o,updated_at=now() where id=:i").param("p",q.parentId()).param("c",q.code()).param("n",q.name()).param("d",q.description()).param("o",q.sortOrder()==null?0:q.sortOrder()).param("i",id).update();support.audit(p,"CATEGORY_UPDATED","CATEGORY",id);return one(p,id);}
 @PatchMapping("/api/v1/categories/{id}/status") @Transactional @PreAuthorize("hasAuthority('CATALOG_CATEGORIES_UPDATE')") Category active(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@RequestBody Active q){support.category(p,id);db.sql("update categories set active=:a,updated_at=now() where id=:i").param("a",q.active()).param("i",id).update();support.audit(p,"CATEGORY_UPDATED","CATEGORY",id);return one(p,id);}
 @DeleteMapping("/api/v1/categories/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_CATEGORIES_DELETE')") void delete(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){support.category(p,id);if(db.sql("select count(*) from products where tenant_id=:t and category_id=:i and status<>'ARCHIVED'").param("t",p.tenantId()).param("i",id).query(Integer.class).single()>0)throw new ApiException(HttpStatus.CONFLICT,"CATEGORY_HAS_PRODUCTS","Desactiva o mueve los productos antes de eliminar la categoría");db.sql("update categories set active=false,updated_at=now() where id=:i").param("i",id).update();support.audit(p,"CATEGORY_DELETED","CATEGORY",id);}
 private void validateParent(IdentityPrincipal p,UUID merchant,UUID current,UUID parent){if(parent==null)return;if(parent.equals(current))throw new ApiException(HttpStatus.BAD_REQUEST,"CATEGORY_CYCLE","Una categoría no puede ser su propio padre");int n=db.sql("select count(*) from categories where id=:p and tenant_id=:t and merchant_id=:m and parent_id is null").param("p",parent).param("t",p.tenantId()).param("m",merchant).query(Integer.class).single();if(n==0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_CATEGORY_PARENT","La categoría padre debe ser del mismo comercio y de primer nivel");}private Category map(java.sql.ResultSet r)throws java.sql.SQLException{return new Category(r.getObject("id",UUID.class),r.getObject("merchant_id",UUID.class),r.getObject("parent_id",UUID.class),r.getString("code"),r.getString("name"),r.getString("description"),r.getInt("sort_order"),r.getBoolean("active"));}}
