package com.delivery.platform.orders.api;
import com.delivery.platform.identity.security.IdentityPrincipal;import com.delivery.platform.orders.application.OrdersService;import com.delivery.platform.orders.domain.OrderModels.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.util.*;
@RestController @RequestMapping("/api/v1") public class OrdersController {private final OrdersService service;public OrdersController(OrdersService service){this.service=service;}
 public record AddItem(@NotNull UUID merchantId,@NotNull UUID branchId,@NotNull UUID productId,@Min(1)int quantity,@Size(max=500)String notes){}public record UpdateItem(@Min(1)int quantity,@Size(max=500)String notes){}public record Checkout(@NotNull UUID deliveryAddressId,@Size(max=1000)String notes){}public record ChangeStatus(@NotNull com.delivery.platform.orders.domain.OrderStatus status,@Size(max=500)String notes){}public record SaveAddress(@NotBlank String label,@NotBlank String recipientName,@NotBlank String phone,@NotBlank String addressLine,String district,String province,String department,@Pattern(regexp="[A-Z]{2}")String countryCode,String postalCode,BigDecimal latitude,BigDecimal longitude,String reference){}
 @GetMapping("/cart") @PreAuthorize("hasAuthority('ORDERS_CART_VIEW')") Cart cart(@AuthenticationPrincipal IdentityPrincipal p){return service.cart(p);}
 @PostMapping("/cart/items") @PreAuthorize("hasAuthority('ORDERS_CART_MANAGE')") Cart add(@AuthenticationPrincipal IdentityPrincipal p,@Valid @RequestBody AddItem q){return service.add(p,q.merchantId(),q.branchId(),q.productId(),q.quantity(),q.notes());}
 @PutMapping("/cart/items/{id}") @PreAuthorize("hasAuthority('ORDERS_CART_MANAGE')") Cart update(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody UpdateItem q){return service.update(p,id,q.quantity(),q.notes());}
 @DeleteMapping("/cart/items/{id}") @PreAuthorize("hasAuthority('ORDERS_CART_MANAGE')") Cart remove(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){return service.remove(p,id);}
 @DeleteMapping("/cart") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAuthority('ORDERS_CART_MANAGE')") void clear(@AuthenticationPrincipal IdentityPrincipal p){service.clear(p);}
 @GetMapping("/delivery-addresses") @PreAuthorize("hasAuthority('ORDERS_VIEW')") List<DeliveryAddress> addresses(@AuthenticationPrincipal IdentityPrincipal p){return service.addresses(p);}
 @PostMapping("/delivery-addresses") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('ORDERS_CREATE')") DeliveryAddress address(@AuthenticationPrincipal IdentityPrincipal p,@Valid @RequestBody SaveAddress q){return service.createAddress(p,new DeliveryAddress(null,q.label(),q.recipientName(),q.phone(),q.addressLine(),q.district(),q.province(),q.department(),q.countryCode()==null?"PE":q.countryCode(),q.postalCode(),q.latitude(),q.longitude(),q.reference(),true));}
 @PostMapping("/orders") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('ORDERS_CREATE')") Order checkout(@AuthenticationPrincipal IdentityPrincipal p,@Valid @RequestBody Checkout q){return service.checkout(p,q.deliveryAddressId(),q.notes());}
 @GetMapping("/orders") @PreAuthorize("hasAuthority('ORDERS_VIEW')") List<Order> orders(@AuthenticationPrincipal IdentityPrincipal p){return service.orders(p);}
 @GetMapping("/orders/{id}") @PreAuthorize("hasAuthority('ORDERS_VIEW')") Order order(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){return service.order(p,id);}
 @PatchMapping("/orders/{id}/status") @PreAuthorize("hasAuthority('ORDERS_STATUS_UPDATE')") Order status(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody ChangeStatus q){return service.status(p,id,q.status(),q.notes());}
 @GetMapping("/orders/history") @PreAuthorize("hasAuthority('ORDERS_VIEW')") List<Order> history(@AuthenticationPrincipal IdentityPrincipal p){return service.orders(p);}
}
