package com.delivery.platform.catalog.merchant.api;
import com.delivery.platform.common.PageResponse;
import com.delivery.platform.catalog.common.CatalogSupport;import com.delivery.platform.common.ApiException;import com.delivery.platform.identity.security.IdentityPrincipal;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/merchants") public class MerchantController {private final JdbcClient db;private final CatalogSupport support;public MerchantController(JdbcClient db,CatalogSupport s){this.db=db;support=s;}
 public record Merchant(UUID id,String code,String name,String legalName,String description,String merchantType,String email,String phone,String status,String defaultCurrency,String timezone,String logoObjectKey,String bannerObjectKey){}public record Save(@NotBlank String code,@NotBlank String name,String legalName,String description,@Pattern(regexp="RESTAURANT|GROCERY|PHARMACY|RETAIL|DARK_STORE|OTHER")String merchantType,String email,String phone,@Pattern(regexp="[A-Z]{3}")String defaultCurrency,@NotBlank String timezone){}public record Status(@Pattern(regexp="DRAFT|ACTIVE|INACTIVE|SUSPENDED")String status){}
 @GetMapping @PreAuthorize("hasAuthority('CATALOG_MERCHANTS_VIEW')") PageResponse<Merchant> list(@AuthenticationPrincipal IdentityPrincipal p,@RequestParam(defaultValue="")String search,@RequestParam(required=false)String status,@RequestParam(required=false)String merchantType,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){int safe=Math.min(Math.max(size,1),100),current=Math.max(page,0);String where=" from merchants where tenant_id=:t and (:q='' or lower(name||' '||code) like lower('%'||:q||'%')) and (cast(:s as varchar) is null or status=:s) and (cast(:m as varchar) is null or merchant_type=:m)";var rows=db.sql("select *"+where+" order by created_at desc limit :z offset :o").param("t",p.tenantId()).param("q",search).param("s",status).param("m",merchantType).param("z",safe).param("o",current*safe).query((r,n)->map(r)).list();long total=db.sql("select count(*)"+where).param("t",p.tenantId()).param("q",search).param("s",status).param("m",merchantType).query(Long.class).single();return PageResponse.of(rows,current,safe,total);}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('CATALOG_MERCHANTS_VIEW')") Merchant one(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){support.merchant(p,id);return db.sql("select * from merchants where id=:i").param("i",id).query((r,n)->map(r)).single();}
 @PostMapping @Transactional @PreAuthorize("hasAuthority('CATALOG_MERCHANTS_CREATE')") Merchant create(@AuthenticationPrincipal IdentityPrincipal p,@Valid @RequestBody Save q){UUID id=UUID.randomUUID();try{db.sql("insert into merchants(id,tenant_id,code,name,legal_name,description,merchant_type,email,phone,default_currency,timezone) values(:i,:t,lower(:c),:n,:l,:d,:m,:e,:p,:u,:z)").param("i",id).param("t",p.tenantId()).param("c",q.code()).param("n",q.name()).param("l",q.legalName()).param("d",q.description()).param("m",q.merchantType()).param("e",q.email()).param("p",q.phone()).param("u",q.defaultCurrency()).param("z",q.timezone()).update();}catch(DataIntegrityViolationException e){throw support.conflict("DUPLICATE_CODE","Ya existe un comercio con ese código");}support.audit(p,"MERCHANT_CREATED","MERCHANT",id);return one(p,id);}
 @PutMapping("/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_MERCHANTS_UPDATE')") Merchant update(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody Save q){support.merchant(p,id);db.sql("update merchants set code=lower(:c),name=:n,legal_name=:l,description=:d,merchant_type=:m,email=:e,phone=:p,default_currency=:u,timezone=:z,updated_at=now() where id=:i").param("c",q.code()).param("n",q.name()).param("l",q.legalName()).param("d",q.description()).param("m",q.merchantType()).param("e",q.email()).param("p",q.phone()).param("u",q.defaultCurrency()).param("z",q.timezone()).param("i",id).update();support.audit(p,"MERCHANT_UPDATED","MERCHANT",id);return one(p,id);}
 @PatchMapping("/{id}/status") @Transactional @PreAuthorize("hasAuthority('CATALOG_MERCHANTS_DISABLE')") Merchant status(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody Status q){support.merchant(p,id);db.sql("update merchants set status=:s,updated_at=now() where id=:i").param("s",q.status()).param("i",id).update();support.audit(p,"MERCHANT_STATUS_CHANGED","MERCHANT",id);return one(p,id);}
 @DeleteMapping("/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_MERCHANTS_DISABLE')") void disable(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){status(p,id,new Status("INACTIVE"));}
 private Merchant map(java.sql.ResultSet r)throws java.sql.SQLException{return new Merchant(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("legal_name"),r.getString("description"),r.getString("merchant_type"),r.getString("email"),r.getString("phone"),r.getString("status"),r.getString("default_currency"),r.getString("timezone"),r.getString("logo_object_key"),r.getString("banner_object_key"));}}
