package com.delivery.platform.catalog.option.api;

import com.delivery.platform.catalog.common.CatalogSupport;
import com.delivery.platform.common.ApiException;
import com.delivery.platform.identity.security.IdentityPrincipal;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.*;

@RestController public class OptionController {
 private final JdbcClient db; private final CatalogSupport support;
 public OptionController(JdbcClient db,CatalogSupport support){this.db=db;this.support=support;}
 public record Group(UUID id,UUID merchantId,String name,String description,String selectionType,boolean required,int minimumSelections,Integer maximumSelections,boolean active,List<Item> items){}
 public record Item(UUID id,UUID optionGroupId,String name,BigDecimal priceAdjustment,boolean available,boolean active,int sortOrder){}
 public record SaveGroup(@NotBlank String name,String description,@Pattern(regexp="SINGLE|MULTIPLE")String selectionType,boolean required,@Min(0)int minimumSelections,@Min(0)Integer maximumSelections,Boolean active){}
 public record SaveItem(@NotBlank String name,@NotNull @DecimalMin("0")BigDecimal priceAdjustment,boolean available,Integer sortOrder){}
 public record ProductGroups(@NotNull List<UUID> optionGroupIds){}

 @GetMapping("/api/v1/merchants/{merchantId}/option-groups") @PreAuthorize("hasAuthority('CATALOG_OPTIONS_VIEW')")
 public List<Group> list(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID merchantId){support.merchant(p,merchantId);return db.sql("select * from option_groups where tenant_id=:t and merchant_id=:m and active order by name").param("t",p.tenantId()).param("m",merchantId).query((r,n)->mapGroup(r)).list();}
 @PostMapping("/api/v1/merchants/{merchantId}/option-groups") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')")
 public Group create(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID merchantId,@Valid @RequestBody SaveGroup q){support.merchant(p,merchantId);validate(q);UUID id=UUID.randomUUID();db.sql("insert into option_groups(id,tenant_id,merchant_id,name,description,selection_type,required,minimum_selections,maximum_selections,active) values(:i,:t,:m,:n,:d,:s,:r,:x,:y,:a)").param("i",id).param("t",p.tenantId()).param("m",merchantId).param("n",q.name()).param("d",q.description()).param("s",q.selectionType()).param("r",q.required()).param("x",q.minimumSelections()).param("y",q.maximumSelections()).param("a",q.active()==null||q.active()).update();support.audit(p,"OPTION_GROUP_CREATED","OPTION_GROUP",id);return one(p,id);}
 @GetMapping("/api/v1/option-groups/{id}") @PreAuthorize("hasAuthority('CATALOG_OPTIONS_VIEW')") public Group one(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){return db.sql("select * from option_groups where id=:i and tenant_id=:t").param("i",id).param("t",p.tenantId()).query((r,n)->mapGroup(r)).optional().orElseThrow(()->missing("OPTION_GROUP_NOT_FOUND","Grupo de opciones no encontrado"));}
 @PutMapping("/api/v1/option-groups/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')") public Group update(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody SaveGroup q){one(p,id);validate(q);db.sql("update option_groups set name=:n,description=:d,selection_type=:s,required=:r,minimum_selections=:x,maximum_selections=:y,active=:a,updated_at=now() where id=:i").param("n",q.name()).param("d",q.description()).param("s",q.selectionType()).param("r",q.required()).param("x",q.minimumSelections()).param("y",q.maximumSelections()).param("a",q.active()==null||q.active()).param("i",id).update();support.audit(p,"OPTION_GROUP_UPDATED","OPTION_GROUP",id);return one(p,id);}
 @DeleteMapping("/api/v1/option-groups/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')") public void delete(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){one(p,id);db.sql("update option_groups set active=false,updated_at=now() where id=:i").param("i",id).update();support.audit(p,"OPTION_GROUP_DELETED","OPTION_GROUP",id);}
 @PostMapping("/api/v1/option-groups/{id}/items") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')") public Item createItem(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody SaveItem q){one(p,id);UUID item=UUID.randomUUID();db.sql("insert into option_items(id,tenant_id,option_group_id,name,price_adjustment,available,sort_order) values(:i,:t,:g,:n,:p,:a,:o)").param("i",item).param("t",p.tenantId()).param("g",id).param("n",q.name()).param("p",q.priceAdjustment()).param("a",q.available()).param("o",q.sortOrder()==null?0:q.sortOrder()).update();support.audit(p,"OPTION_GROUP_UPDATED","OPTION_ITEM",item);return item(p,item);}
 @PutMapping("/api/v1/option-items/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')") public Item updateItem(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody SaveItem q){item(p,id);db.sql("update option_items set name=:n,price_adjustment=:p,available=:a,sort_order=:o,updated_at=now() where id=:i").param("n",q.name()).param("p",q.priceAdjustment()).param("a",q.available()).param("o",q.sortOrder()==null?0:q.sortOrder()).param("i",id).update();return item(p,id);}
 @DeleteMapping("/api/v1/option-items/{id}") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')") public void deleteItem(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){item(p,id);db.sql("update option_items set active=false,available=false,updated_at=now() where id=:i").param("i",id).update();}
 @GetMapping("/api/v1/products/{productId}/option-groups") @PreAuthorize("hasAuthority('CATALOG_OPTIONS_VIEW')") public List<Group> assigned(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID productId){support.product(p,productId);return db.sql("select g.* from option_groups g join product_option_groups pg on pg.option_group_id=g.id where pg.product_id=:p and g.tenant_id=:t and g.active order by pg.sort_order").param("p",productId).param("t",p.tenantId()).query((r,n)->mapGroup(r)).list();}
 @PutMapping("/api/v1/products/{productId}/option-groups") @Transactional @PreAuthorize("hasAuthority('CATALOG_OPTIONS_MANAGE')") public List<Group> assign(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID productId,@RequestBody ProductGroups q){support.product(p,productId);UUID merchant=db.sql("select merchant_id from products where id=:i").param("i",productId).query(UUID.class).single();db.sql("delete from product_option_groups where product_id=:p").param("p",productId).update();int order=0;for(UUID group:q.optionGroupIds()){int valid=db.sql("select count(*) from option_groups where id=:g and tenant_id=:t and merchant_id=:m and active").param("g",group).param("t",p.tenantId()).param("m",merchant).query(Integer.class).single();if(valid==0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTION_GROUP","El grupo debe pertenecer al mismo comercio");db.sql("insert into product_option_groups(product_id,option_group_id,sort_order) values(:p,:g,:o)").param("p",productId).param("g",group).param("o",order++).update();}support.audit(p,"PRODUCT_UPDATED","PRODUCT",productId);return db.sql("select g.* from option_groups g join product_option_groups pg on pg.option_group_id=g.id where pg.product_id=:p order by pg.sort_order").param("p",productId).query((r,n)->mapGroup(r)).list();}
 private void validate(SaveGroup q){if(q.maximumSelections()!=null&&q.maximumSelections()<q.minimumSelections())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTION_GROUP","El máximo debe ser mayor o igual al mínimo");if("SINGLE".equals(q.selectionType())&&q.maximumSelections()!=null&&q.maximumSelections()>1)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTION_GROUP","La selección única permite como máximo una opción");}
 private Group mapGroup(java.sql.ResultSet r)throws java.sql.SQLException{UUID id=r.getObject("id",UUID.class);return new Group(id,r.getObject("merchant_id",UUID.class),r.getString("name"),r.getString("description"),r.getString("selection_type"),r.getBoolean("required"),r.getInt("minimum_selections"),(Integer)r.getObject("maximum_selections"),r.getBoolean("active"),db.sql("select * from option_items where option_group_id=:g and active order by sort_order,name").param("g",id).query((x,n)->mapItem(x)).list());}
 private Item item(IdentityPrincipal p,UUID id){return db.sql("select * from option_items where id=:i and tenant_id=:t").param("i",id).param("t",p.tenantId()).query((r,n)->mapItem(r)).optional().orElseThrow(()->missing("OPTION_ITEM_NOT_FOUND","Complemento no encontrado"));}private Item mapItem(java.sql.ResultSet r)throws java.sql.SQLException{return new Item(r.getObject("id",UUID.class),r.getObject("option_group_id",UUID.class),r.getString("name"),r.getBigDecimal("price_adjustment"),r.getBoolean("available"),r.getBoolean("active"),r.getInt("sort_order"));}private ApiException missing(String c,String m){return new ApiException(HttpStatus.NOT_FOUND,c,m);}
}
