'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {AlertCircle} from 'lucide-react';
import {api,ApiClientError} from '@/lib/api';
import type {Cart} from '@/lib/orders';
import {EmptyCart,PriceBreakdown,ProductLine} from '@/components/orders/OrderComponents';
type Merchant={id:string;name:string;status:string};type Branch={id:string;name:string;status:string};type Product={id:string;name:string;basePrice:number;currency:string;status:string;available:boolean};
export default function CartPage(){
 const[cart,setCart]=useState<Cart|null>(null),[merchants,setMerchants]=useState<Merchant[]>([]),[branches,setBranches]=useState<Branch[]>([]),[products,setProducts]=useState<Product[]>([]);const[merchant,setMerchant]=useState(''),[branch,setBranch]=useState(''),[product,setProduct]=useState(''),[quantity,setQuantity]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(()=>api<Cart|null>('/api/v1/cart').then(setCart).catch(cause=>setError(cause.message)),[]);
 useEffect(()=>{void load();api<{content:Merchant[]}>('/api/v1/merchants?size=100').then(page=>setMerchants(page.content)).catch(cause=>setError(cause instanceof Error?cause.message:'No se pudieron cargar los comercios.'))},[load]);
 const selectedMerchant=merchants.find(item=>item.id===merchant),merchantReady=selectedMerchant?.status==='ACTIVE';
 useEffect(()=>{if(!merchant||!merchantReady){setBranches([]);return}api<Branch[]>(`/api/v1/merchants/${merchant}/branches`).then(setBranches).catch(cause=>setError(cause instanceof Error?cause.message:'No se pudieron cargar las sucursales.'))},[merchant,merchantReady]);
 useEffect(()=>{if(!branch){setProducts([]);return}api<{content:Product[]}>(`/api/v1/merchants/${merchant}/products?status=PUBLISHED&size=100`).then(page=>setProducts(page.content.filter(item=>item.available))).catch(cause=>setError(cause instanceof Error?cause.message:'No se pudieron cargar los productos.'))},[branch,merchant]);
 async function add(event:FormEvent){event.preventDefault();if(!merchant||!branch||!product)return;setBusy(true);setError('');try{setCart(await api<Cart>('/api/v1/cart/items',{method:'POST',body:JSON.stringify({merchantId:merchant,branchId:branch,productId:product,quantity})}));setProduct('');setQuantity(1)}catch(cause){setError(cause instanceof ApiClientError?cause.message:'No se pudo agregar el producto')}finally{setBusy(false)}}
 async function update(id:string,value:number){setBusy(true);try{setCart(await api<Cart>(`/api/v1/cart/items/${id}`,{method:'PUT',body:JSON.stringify({quantity:value})}))}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo actualizar')}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);try{setCart(await api<Cart>(`/api/v1/cart/items/${id}`,{method:'DELETE'}))}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo eliminar el producto.')}finally{setBusy(false)}}
 return <><div className="title"><div><p className="eyebrow">PEDIDOS</p><h1>Carrito</h1><p>Los precios y totales se validan siempre en el servidor.</p></div></div>{error&&<div className="form-alert" role="alert">{error}</div>}<div className="cart-layout"><section className="stack"><form className="panel add-product-form" onSubmit={add}><h2>Agregar producto</h2><label>Comercio<select value={merchant} disabled={!!cart?.items.length} onChange={event=>{setMerchant(event.target.value);setBranch('');setProduct('')}}><option value="">Seleccionar</option>{merchants.map(item=><option value={item.id} key={item.id}>{item.name} · {item.status}</option>)}</select>{!merchants.length&&<small className="field-helper">No hay comercios registrados para tu empresa.</small>}</label><label>Sucursal<select value={branch} disabled={!merchantReady||!!cart?.items.length} onChange={event=>setBranch(event.target.value)}><option value="">{merchant&&!merchantReady?'Activa primero el comercio':'Seleccionar'}</option>{branches.map(item=><option value={item.id} key={item.id} disabled={item.status!=='ACTIVE'}>{item.name} · {item.status}</option>)}</select></label>{selectedMerchant&&!merchantReady&&<div className="cart-catalog-warning"><AlertCircle size={18}/><span><strong>{selectedMerchant.name} todavía está en estado {selectedMerchant.status}.</strong> Debes activarlo antes de agregar productos al carrito.</span><Link href={`/merchants/${selectedMerchant.id}`}>Administrar comercio</Link></div>}<label>Producto<select value={product} disabled={!branch} onChange={event=>setProduct(event.target.value)}><option value="">Seleccionar</option>{products.map(item=><option value={item.id} key={item.id}>{item.name} · {item.currency} {item.basePrice}</option>)}</select>{branch&&!products.length&&<small className="field-helper">No hay productos publicados y disponibles.</small>}</label><label>Cantidad<input type="number" min="1" value={quantity} onChange={event=>setQuantity(Math.max(1,Number(event.target.value)))}/></label><button disabled={busy||!product}>{busy?'Agregando…':'Agregar al carrito'}</button></form><section className="panel cart-items">{!cart?.items.length?<EmptyCart/>:cart.items.map(item=><ProductLine key={item.id} item={item} currency={cart.currency} busy={busy} onQuantity={value=>update(item.id,value)} onRemove={()=>remove(item.id)}/>)}</section></section><aside className="panel cart-summary"><h2>Resumen</h2>{cart?<PriceBreakdown {...cart}/>:<PriceBreakdown subtotal={0} discount={0} tax={0} deliveryFee={0} total={0} currency="PEN"/>}<Link className={`button checkout-button ${!cart?.items.length?'is-disabled':''}`} aria-disabled={!cart?.items.length} href={cart?.items.length?'/checkout':'/cart'}>Continuar al checkout</Link></aside></div></>}
