package com.delivery.platform.catalog.media.infrastructure;
import io.minio.*;import io.minio.http.Method;import jakarta.annotation.PostConstruct;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Component;import org.springframework.web.multipart.MultipartFile;import java.io.InputStream;import java.util.*;import java.util.concurrent.TimeUnit;
@Component public class MinioCatalogStorage {private final MinioClient client;private final MinioClient signer;private final String bucket;private final long maxBytes;public MinioCatalogStorage(@Value("${MINIO_ENDPOINT:http://localhost:9000}")String endpoint,@Value("${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}")String publicEndpoint,@Value("${MINIO_ACCESS_KEY:delivery}")String access,@Value("${MINIO_SECRET_KEY:delivery_minio_password}")String secret,@Value("${MINIO_BUCKET_CATALOG:delivery-catalog}")String bucket,@Value("${CATALOG_MAX_IMAGE_SIZE_MB:5}")long maxMb){client=MinioClient.builder().endpoint(endpoint).credentials(access,secret).build();signer=MinioClient.builder().endpoint(publicEndpoint).credentials(access,secret).build();this.bucket=bucket;maxBytes=maxMb*1024*1024;}
 @PostConstruct public void initialize(){try{if(!client.bucketExists(BucketExistsArgs.builder().bucket(bucket).build()))client.makeBucket(MakeBucketArgs.builder().bucket(bucket).build());}catch(Exception e){throw new IllegalStateException("No se pudo inicializar el bucket de catálogo",e);}}
 public String put(UUID tenant,String folder,MultipartFile file){String type=file.getContentType();if(!Set.of("image/jpeg","image/png","image/webp").contains(type))throw new MediaException("MEDIA_TYPE_NOT_ALLOWED","Solo se permiten imágenes JPEG, PNG o WebP");if(file.isEmpty()||file.getSize()>maxBytes)throw new MediaException("MEDIA_TOO_LARGE","La imagen supera el tamaño máximo permitido");String ext=switch(type){case"image/jpeg"->"jpg";case"image/png"->"png";default->"webp";};String key="tenant/"+tenant+"/"+folder+"/"+UUID.randomUUID()+"."+ext;try(InputStream in=file.getInputStream()){client.putObject(PutObjectArgs.builder().bucket(bucket).object(key).stream(in,file.getSize(),-1).contentType(type).build());return key;}catch(Exception e){throw new MediaException("MEDIA_UPLOAD_FAILED","No se pudo guardar la imagen");}}
 public String signedUrl(String key){try{return signer.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder().method(Method.GET).bucket(bucket).object(key).expiry(15,TimeUnit.MINUTES).build());}catch(Exception e){throw new MediaException("MEDIA_URL_FAILED","No se pudo generar la URL de imagen");}}
 public void delete(String key){try{client.removeObject(RemoveObjectArgs.builder().bucket(bucket).object(key).build());}catch(Exception e){throw new MediaException("MEDIA_DELETE_FAILED","No se pudo eliminar la imagen");}}
 public static class MediaException extends RuntimeException{public final String code;public MediaException(String c,String m){super(m);code=c;}}
}
