package com.delivery.platform.identity.user.api;
import com.delivery.platform.common.ApiException; import com.delivery.platform.identity.security.IdentityPrincipal; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/users") public class UserController {private final JdbcClient db;private final PasswordEncoder encoder;public UserController(JdbcClient d,PasswordEncoder e){db=d;encoder=e;}
 public record UserDto(UUID id,String email,String firstName,String lastName,String phone,String status,List<String> roles){} public record Create(@Email @NotBlank String email,@Size(min=10)String password,@NotBlank String firstName,@NotBlank String lastName,String phone,Set<UUID> roleIds){} public record Update(@NotBlank String firstName,@NotBlank String lastName,String phone){} public record Status(@Pattern(regexp="ACTIVE|INACTIVE|LOCKED")String status){} public record Roles(Set<UUID> roleIds){}
 @GetMapping @PreAuthorize("hasAuthority('IDENTITY_USERS_VIEW')") List<UserDto> list(@AuthenticationPrincipal IdentityPrincipal p,@RequestParam(defaultValue="")String search,@RequestParam(required=false)String status){return db.sql("select u.id,u.email,u.first_name,u.last_name,u.phone,u.status from users u where u.tenant_id=:t and (:s='' or lower(u.email||' '||u.first_name||' '||u.last_name) like lower('%'||:s||'%')) and (cast(:st as varchar) is null or u.status=:st) order by u.created_at desc limit 100").param("t",p.tenantId()).param("s",search).param("st",status).query((rs,n)->dto(rs.getObject("id",UUID.class),rs.getString("email"),rs.getString("first_name"),rs.getString("last_name"),rs.getString("phone"),rs.getString("status"))).list();}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('IDENTITY_USERS_VIEW')") UserDto one(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){return db.sql("select id,email,first_name,last_name,phone,status from users where id=:id and tenant_id=:t").param("id",id).param("t",p.tenantId()).query((rs,n)->dto(id,rs.getString("email"),rs.getString("first_name"),rs.getString("last_name"),rs.getString("phone"),rs.getString("status"))).optional().orElseThrow(()->missing());}
 @PostMapping @Transactional @PreAuthorize("hasAuthority('IDENTITY_USERS_CREATE')") UserDto create(@AuthenticationPrincipal IdentityPrincipal p,@Valid @RequestBody Create q){UUID id=UUID.randomUUID();try{db.sql("insert into users(id,tenant_id,email,password_hash,first_name,last_name,phone,status) values(:id,:t,lower(:e),:pw,:f,:l,:ph,'ACTIVE')").param("id",id).param("t",p.tenantId()).param("e",q.email()).param("pw",encoder.encode(q.password())).param("f",q.firstName()).param("l",q.lastName()).param("ph",q.phone()).update();assign(p,id,q.roleIds());audit(p,"USER_CREATED",id);}catch(org.springframework.dao.DataIntegrityViolationException e){throw new ApiException(HttpStatus.CONFLICT,"USER_EXISTS","El correo ya está registrado");}return one(p,id);}
 @PutMapping("/{id}") @Transactional @PreAuthorize("hasAuthority('IDENTITY_USERS_UPDATE')") UserDto update(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody Update q){owned(p,id);db.sql("update users set first_name=:f,last_name=:l,phone=:ph,updated_at=now() where id=:id").param("f",q.firstName()).param("l",q.lastName()).param("ph",q.phone()).param("id",id).update();audit(p,"USER_UPDATED",id);return one(p,id);}
 @PatchMapping("/{id}/status") @Transactional @PreAuthorize("hasAuthority('IDENTITY_USERS_DISABLE')") UserDto status(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody Status q){owned(p,id);if(id.equals(p.userId())&&!"ACTIVE".equals(q.status())&&isLastAdmin(p,id))throw new ApiException(HttpStatus.CONFLICT,"LAST_TENANT_ADMIN","No se puede desactivar el último administrador activo");db.sql("update users set status=:s,updated_at=now() where id=:id").param("s",q.status()).param("id",id).update();audit(p,"USER_STATUS_CHANGED",id);return one(p,id);}
 @PutMapping("/{id}/roles") @Transactional @PreAuthorize("hasAuthority('IDENTITY_ROLES_ASSIGN')") UserDto roles(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@RequestBody Roles q){owned(p,id);assign(p,id,q.roleIds());audit(p,"USER_ROLES_UPDATED",id);return one(p,id);}
 private void assign(IdentityPrincipal p,UUID u,Set<UUID> ids){db.sql("delete from user_roles where user_id=:u").param("u",u).update();if(ids==null)return;for(UUID r:ids){int ok=db.sql("select count(*) from roles where id=:r and tenant_id=:t and code<>'PLATFORM_ADMIN'").param("r",r).param("t",p.tenantId()).query(Integer.class).single();if(ok==0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_ROLE","Rol no permitido");db.sql("insert into user_roles values(:u,:r)").param("u",u).param("r",r).update();}}
 private UserDto dto(UUID id,String e,String f,String l,String ph,String s){return new UserDto(id,e,f,l,ph,s,db.sql("select r.code from roles r join user_roles ur on ur.role_id=r.id where ur.user_id=:u").param("u",id).query(String.class).list());}private void owned(IdentityPrincipal p,UUID id){if(db.sql("select count(*) from users where id=:i and tenant_id=:t").param("i",id).param("t",p.tenantId()).query(Integer.class).single()==0)throw missing();}private boolean isLastAdmin(IdentityPrincipal p,UUID id){return db.sql("select count(*) from users u join user_roles ur on ur.user_id=u.id join roles r on r.id=ur.role_id where u.tenant_id=:t and u.status='ACTIVE' and r.code='TENANT_ADMIN'").param("t",p.tenantId()).query(Integer.class).single()<=1;}private ApiException missing(){return new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","Usuario no encontrado");}private void audit(IdentityPrincipal p,String a,UUID e){db.sql("insert into audit_logs(tenant_id,user_id,action,entity_type,entity_id) values(:t,:u,:a,'USER',:e)").param("t",p.tenantId()).param("u",p.userId()).param("a",a).param("e",e).update();}
}
