package com.delivery.platform.identity.role.api;
import com.delivery.platform.common.ApiException; import com.delivery.platform.identity.security.IdentityPrincipal; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/roles") public class RoleController {private final JdbcClient db;public RoleController(JdbcClient d){db=d;}public record Role(UUID id,String code,String name,String description,boolean systemRole,boolean active,List<String> permissions){}public record Save(@NotBlank @Pattern(regexp="[A-Z][A-Z0-9_]*")String code,@NotBlank String name,String description,Boolean active){}public record Permissions(Set<UUID> permissionIds){}
 @GetMapping @PreAuthorize("hasAuthority('IDENTITY_ROLES_VIEW')") List<Role> list(@AuthenticationPrincipal IdentityPrincipal p){return db.sql("select id,code,name,description,system_role,active from roles where tenant_id=:t order by name").param("t",p.tenantId()).query((r,n)->dto(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("description"),r.getBoolean("system_role"),r.getBoolean("active"))).list();}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('IDENTITY_ROLES_VIEW')") Role one(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id){return db.sql("select id,code,name,description,system_role,active from roles where tenant_id=:t and id=:id").param("t",p.tenantId()).param("id",id).query((r,n)->dto(id,r.getString("code"),r.getString("name"),r.getString("description"),r.getBoolean("system_role"),r.getBoolean("active"))).optional().orElseThrow(this::missing);}
 @PostMapping @Transactional @PreAuthorize("hasAuthority('IDENTITY_ROLES_CREATE')") Role create(@AuthenticationPrincipal IdentityPrincipal p,@Valid @RequestBody Save q){UUID id=UUID.randomUUID();db.sql("insert into roles(id,tenant_id,code,name,description,active) values(:i,:t,:c,:n,:d,:a)").param("i",id).param("t",p.tenantId()).param("c",q.code()).param("n",q.name()).param("d",q.description()).param("a",q.active()==null||q.active()).update();audit(p,"ROLE_CREATED",id);return one(p,id);}
 @PutMapping("/{id}") @Transactional @PreAuthorize("hasAuthority('IDENTITY_ROLES_UPDATE')") Role update(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@Valid @RequestBody Save q){Role old=one(p,id);if(old.systemRole())throw new ApiException(HttpStatus.FORBIDDEN,"SYSTEM_ROLE","No se puede modificar un rol de sistema");int changed=db.sql("update roles set code=:c,name=:n,description=:d,active=:a,updated_at=now() where id=:i and tenant_id=:t").param("c",q.code()).param("n",q.name()).param("d",q.description()).param("a",q.active()==null||q.active()).param("i",id).param("t",p.tenantId()).update();if(changed!=1)throw missing();audit(p,"ROLE_UPDATED",id);return one(p,id);}
 @PutMapping("/{id}/permissions") @Transactional @PreAuthorize("hasAuthority('IDENTITY_ROLES_UPDATE')") Role permissions(@AuthenticationPrincipal IdentityPrincipal p,@PathVariable UUID id,@RequestBody Permissions q){Role old=one(p,id);if(old.systemRole())throw new ApiException(HttpStatus.FORBIDDEN,"SYSTEM_ROLE","No se puede modificar un rol de sistema");db.sql("delete from role_permissions rp using roles r where rp.role_id=r.id and r.id=:r and r.tenant_id=:t").param("r",id).param("t",p.tenantId()).update();if(q.permissionIds()!=null)q.permissionIds().forEach(x->{int inserted=db.sql("insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r join permissions p on p.id=:p where r.id=:r and r.tenant_id=:t").param("r",id).param("p",x).param("t",p.tenantId()).update();if(inserted!=1)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PERMISSION","Permiso no permitido");});audit(p,"ROLE_PERMISSIONS_UPDATED",id);return one(p,id);}
 @GetMapping("/permissions/catalog") @PreAuthorize("hasAuthority('IDENTITY_ROLES_VIEW')") Map<String,List<Map<String,Object>>> catalog(){Map<String,List<Map<String,Object>>> out=new LinkedHashMap<>();db.sql("select id,code,module,action,description from permissions order by module,code").query((r,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",r.getObject("id"));m.put("code",r.getString("code"));m.put("action",r.getString("action"));m.put("description",r.getString("description"));out.computeIfAbsent(r.getString("module"),x->new ArrayList<>()).add(m);return 0;}).list();return out;}
 private Role dto(UUID i,String c,String n,String d,boolean s,boolean a){return new Role(i,c,n,d,s,a,db.sql("select p.code from permissions p join role_permissions rp on rp.permission_id=p.id where rp.role_id=:r order by p.code").param("r",i).query(String.class).list());}private ApiException missing(){return new ApiException(HttpStatus.NOT_FOUND,"ROLE_NOT_FOUND","Rol no encontrado");}private void audit(IdentityPrincipal p,String a,UUID e){db.sql("insert into audit_logs(tenant_id,user_id,action,entity_type,entity_id) values(:t,:u,:a,'ROLE',:e)").param("t",p.tenantId()).param("u",p.userId()).param("a",a).param("e",e).update();}
}
