'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {Building2,Crosshair,MapPin,Pencil,Plus,X} from 'lucide-react';
import {api,ApiClientError,FieldErrors} from '@/lib/api';
import {useAuth} from '@/lib/auth';
type Merchant={id:string;name:string;code:string;status:string};
type Branch={id:string;merchantId:string;name:string;code:string;addressLine:string;formattedAddress:string|null;placeId:string|null;district:string|null;city:string|null;province:string|null;region:string|null;countryCode:string;phone:string;status:string;timezone:string;latitude:number|null;longitude:number|null;coverageEnabled:boolean;deliveryRadiusKm:number|null};
type Suggestion={placeId:string;primaryText:string;secondaryText:string;formattedText:string};
type Location={placeId:string;formattedAddress:string;latitude:number;longitude:number;street?:string;streetNumber?:string;district?:string;city?:string;province?:string;region?:string;countryCode?:string};
type Page<T>={content:T[]};
type Form={merchantId:string;code:string;name:string;phone:string;timezone:string;addressLine:string;formattedAddress:string;placeId:string;district:string;city:string;province:string;region:string;countryCode:string;latitude:number|null;longitude:number|null;coverageEnabled:boolean;deliveryRadiusKm:string};
const initial:Form={merchantId:'',code:'',name:'',phone:'',timezone:'America/Lima',addressLine:'',formattedAddress:'',placeId:'',district:'',city:'',province:'',region:'',countryCode:'PE',latitude:null,longitude:null,coverageEnabled:false,deliveryRadiusKm:'3'};
export default function BranchesPage(){
 const{can}=useAuth();const[merchants,setMerchants]=useState<Merchant[]>([]),[branches,setBranches]=useState<Branch[]>([]);const[merchantId,setMerchantId]=useState('');const[form,setForm]=useState<Form>(initial);const[editingId,setEditingId]=useState<string|null>(null);const[showForm,setShowForm]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[searching,setSearching]=useState(false);const[query,setQuery]=useState(''),[sessionToken,setSessionToken]=useState('');const[suggestions,setSuggestions]=useState<Suggestion[]>([]);const[error,setError]=useState('');const[errors,setErrors]=useState<FieldErrors>({});
 const loadBranches=useCallback(async(ids:string[])=>{const lists=await Promise.all(ids.map(id=>api<Branch[]>(`/api/v1/merchants/${id}/branches`)));setBranches(lists.flat())},[]);
 useEffect(()=>{api<Page<Merchant>>('/api/v1/merchants?size=100').then(async({content})=>{setMerchants(content);await loadBranches(content.map(x=>x.id))}).catch(cause=>setError(cause instanceof Error?cause.message:'No se pudieron cargar las sucursales.')).finally(()=>setLoading(false))},[loadBranches]);
 useEffect(()=>{if(query.trim().length<3||!showForm){setSuggestions([]);return}const token=sessionToken||crypto.randomUUID();if(!sessionToken)setSessionToken(token);const timer=window.setTimeout(async()=>{setSearching(true);try{const result=await api<{suggestions:Suggestion[]}>(`/api/v1/admin/locations/search?query=${encodeURIComponent(query)}&sessionToken=${token}`);setSuggestions(result.suggestions)}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo buscar la dirección.')}finally{setSearching(false)}},400);return()=>window.clearTimeout(timer)},[query,sessionToken,showForm]);
 function change<K extends keyof Form>(field:K,value:Form[K]){setForm(current=>({...current,[field]:value}));setErrors(current=>({...current,[field]:''}))}
 function applyLocation(location:Location){const addressLine=[location.street,location.streetNumber].filter(Boolean).join(' ')||location.formattedAddress;setForm(current=>({...current,addressLine,formattedAddress:location.formattedAddress,placeId:location.placeId,latitude:Number(location.latitude),longitude:Number(location.longitude),district:location.district??'',city:location.city??'',province:location.province??'',region:location.region??'',countryCode:location.countryCode??'PE'}));setQuery(location.formattedAddress);setSuggestions([]);setErrors(current=>({...current,addressLine:'',latitude:'',deliveryRadiusKm:''}))}
 async function selectPlace(placeId:string){setSearching(true);setError('');try{applyLocation(await api<Location>(`/api/v1/admin/locations/place/${encodeURIComponent(placeId)}?sessionToken=${sessionToken}`));setSessionToken(crypto.randomUUID())}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo seleccionar la dirección.')}finally{setSearching(false)}}
 async function adjust(latDelta:number,lngDelta:number){if(form.latitude==null||form.longitude==null)return;setSearching(true);try{applyLocation(await api<Location>(`/api/v1/admin/locations/reverse?latitude=${form.latitude+latDelta}&longitude=${form.longitude+lngDelta}`))}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo ajustar el pin.')}finally{setSearching(false)}}
 function openCreate(){setEditingId(null);setForm(initial);setQuery('');setSuggestions([]);setSessionToken(crypto.randomUUID());setErrors({});setShowForm(true)}
 function openEdit(branch:Branch){setEditingId(branch.id);setForm({merchantId:branch.merchantId,code:branch.code,name:branch.name,phone:branch.phone??'',timezone:branch.timezone,addressLine:branch.addressLine,formattedAddress:branch.formattedAddress??branch.addressLine,placeId:branch.placeId??'',district:branch.district??'',city:branch.city??'',province:branch.province??'',region:branch.region??'',countryCode:branch.countryCode??'PE',latitude:branch.latitude,longitude:branch.longitude,coverageEnabled:branch.coverageEnabled,deliveryRadiusKm:branch.deliveryRadiusKm?.toString()??'3'});setQuery(branch.formattedAddress??branch.addressLine);setSessionToken(crypto.randomUUID());setErrors({});setShowForm(true);window.scrollTo({top:0,behavior:'smooth'})}
 async function save(event:FormEvent){event.preventDefault();const next:FieldErrors={};if(!form.merchantId)next.merchantId='Selecciona el comercio.';if(!form.name.trim())next.name='Ingresa el nombre.';if(!/^[a-z0-9-]+$/.test(form.code))next.code='Usa minúsculas, números y guiones.';if(!form.placeId||form.latitude==null||form.longitude==null)next.addressLine='Selecciona una dirección de las sugerencias.';const radius=Number(form.deliveryRadiusKm);if(form.coverageEnabled&&(!Number.isFinite(radius)||radius<=0))next.deliveryRadiusKm='Ingresa un radio mayor que cero.';if(!form.timezone.trim())next.timezone='Ingresa una zona horaria válida.';setErrors(next);if(Object.keys(next).length)return;setSaving(true);setError('');const payload={...form,deliveryRadiusKm:form.coverageEnabled?radius:null};try{if(editingId)await api(`/api/v1/branches/${editingId}`,{method:'PUT',body:JSON.stringify(payload)});else await api(`/api/v1/merchants/${form.merchantId}/branches`,{method:'POST',body:JSON.stringify(payload)});setShowForm(false);setEditingId(null);setForm(initial);await loadBranches(merchants.map(x=>x.id))}catch(cause){if(cause instanceof ApiClientError){setError(cause.message);setErrors(cause.details)}else setError('No se pudo guardar la sucursal.')}finally{setSaving(false)}}
 const visible=merchantId?branches.filter(x=>x.merchantId===merchantId):branches;const merchantName=(id:string)=>merchants.find(x=>x.id===id)?.name??'Comercio';const mapUrl=form.latitude==null||form.longitude==null?null:`https://www.openstreetmap.org/export/embed.html?bbox=${form.longitude-.01}%2C${form.latitude-.01}%2C${form.longitude+.01}%2C${form.latitude+.01}&layer=mapnik&marker=${form.latitude}%2C${form.longitude}`;
 return <><div className="title branch-title"><div><p className="eyebrow">CATÁLOGO</p><h1>Sucursales</h1><p className="muted">Administra ubicaciones y cobertura por comercio.</p></div>{can('CATALOG_BRANCHES_CREATE')&&<button onClick={openCreate}><Plus size={18}/>Nueva sucursal</button>}</div>{error&&<div className="form-alert" role="alert"><strong>No se pudo completar la operación</strong><span>{error}</span></div>}
 {showForm&&<form className="panel catalog-form branch-form" onSubmit={save} noValidate><div className="branch-form-heading full"><div><h2>{editingId?'Editar sucursal':'Nueva sucursal'}</h2><p>Selecciona una ubicación real y define su cobertura.</p></div><button type="button" className="button-link" aria-label="Cerrar formulario" onClick={()=>setShowForm(false)}><X size={20}/></button></div>
 <label>Comercio<select value={form.merchantId} disabled={!!editingId} aria-invalid={!!errors.merchantId} onChange={e=>change('merchantId',e.target.value)}><option value="">Seleccionar comercio</option>{merchants.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{errors.merchantId&&<small className="field-error">{errors.merchantId}</small>}</label><label>Nombre<input value={form.name} aria-invalid={!!errors.name} onChange={e=>change('name',e.target.value)}/>{errors.name&&<small className="field-error">{errors.name}</small>}</label><label>Código<input value={form.code} aria-invalid={!!errors.code} placeholder="trujillo-centro" onChange={e=>change('code',e.target.value.toLowerCase())}/>{errors.code&&<small className="field-error">{errors.code}</small>}</label><label>Teléfono<input value={form.phone} onChange={e=>change('phone',e.target.value)}/></label><label>Zona horaria<input value={form.timezone} aria-invalid={!!errors.timezone} onChange={e=>change('timezone',e.target.value)}/>{errors.timezone&&<small className="field-error">{errors.timezone}</small>}</label>
 <div className="full branch-location-search"><label>Buscar dirección<input value={query} aria-invalid={!!errors.addressLine} autoComplete="off" placeholder="Mercurio 405, Trujillo" onChange={e=>{setQuery(e.target.value);change('placeId','')}}/></label>{searching&&<small>Buscando…</small>}{errors.addressLine&&<small className="field-error">{errors.addressLine}</small>}{suggestions.length>0&&<div className="branch-suggestions">{suggestions.map(item=><button type="button" key={item.placeId} onClick={()=>selectPlace(item.placeId)}><MapPin size={17}/><span><strong>{item.primaryText}</strong><small>{item.secondaryText}</small></span></button>)}</div>}</div>
 {mapUrl&&<div className="full branch-map"><iframe title="Ubicación de la sucursal" src={mapUrl}/><div><strong><MapPin size={17}/>{form.formattedAddress}</strong><span>{form.district}{form.city?` · ${form.city}`:''}</span><small>Ajusta el pin en pasos cortos.</small><div className="pin-adjust"><button type="button" onClick={()=>adjust(.0005,0)}>N</button><button type="button" onClick={()=>adjust(0,-.0005)}>O</button><Crosshair/><button type="button" onClick={()=>adjust(0,.0005)}>E</button><button type="button" onClick={()=>adjust(-.0005,0)}>S</button></div></div></div>}
 <label className="coverage-toggle"><input type="checkbox" checked={form.coverageEnabled} onChange={e=>change('coverageEnabled',e.target.checked)}/>Activar entregas para esta sucursal</label><label>Radio de cobertura (km)<input type="number" min="0.1" step="0.1" disabled={!form.coverageEnabled} value={form.deliveryRadiusKm} aria-invalid={!!errors.deliveryRadiusKm} onChange={e=>change('deliveryRadiusKm',e.target.value)}/>{errors.deliveryRadiusKm&&<small className="field-error">{errors.deliveryRadiusKm}</small>}</label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancelar</button><button disabled={saving||searching}>{saving?'Guardando…':editingId?'Guardar cambios':'Crear sucursal'}</button></div></form>}
 <div className="toolbar branch-filter"><label>Filtrar por comercio<select value={merchantId} onChange={e=>setMerchantId(e.target.value)}><option value="">Todos los comercios</option>{merchants.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><section className="branch-grid">{loading?<div className="panel empty">Cargando sucursales…</div>:visible.length===0?<div className="panel empty"><Building2 size={34}/><strong>Sin sucursales</strong><span>Crea la primera sucursal.</span></div>:visible.map(branch=><article className="panel branch-card" key={branch.id}><div className="branch-card-heading"><div className="branch-icon"><Building2 size={20}/></div><span className={`badge ${branch.status.toLowerCase()}`}>{branch.status}</span></div><div><h2>{branch.name}</h2><p>{merchantName(branch.merchantId)} · {branch.code}</p></div><div className="branch-address"><MapPin size={17}/><span>{branch.formattedAddress??branch.addressLine}</span></div><span className={branch.coverageEnabled?'coverage-ready':'coverage-pending'}>{branch.coverageEnabled?`Cobertura: ${branch.deliveryRadiusKm} km`:'Cobertura pendiente'}</span>{can('CATALOG_BRANCHES_UPDATE')&&<button className="secondary" onClick={()=>openEdit(branch)}><Pencil size={16}/>Editar ubicación</button>}</article>)}</section></>;
}
